import type { Course, Step } from "@/lib/lesson-ir";

/**
 * Course — JavaScript on a Page.
 *
 * The JavaScript course teaches the language. This one teaches the browser:
 * finding an element, changing what it says, and answering a click. Decision
 * 39 exists because that gap was total — across 655 JavaScript steps there was
 * not one `document.`, `querySelector`, `addEventListener`, or `fetch`, so a
 * learner could finish the course having never made a page do anything.
 *
 * Steps here assert with the `page-*` family, which is checked after the
 * learner's script has run (`lib/page-runner.ts`). The plain `exists` and
 * `text-equals` family cannot be used: it runs in a frame where nothing
 * executes, so it would describe the starting markup and say nothing about
 * what the script did. See AGENTS.md rule 1.1.
 */

let n = 0;

/** A page step ships markup and a script. Styles stay out of the way here. */
const page = (html: string, js: string): Record<string, string> => ({
  "index.html": html,
  "script.js": js,
  "styles.css": "",
});

interface StepReference {
  estimatedMinutes: number;
  solution: Record<string, string>;
}

/* dom-topic: find-element */
const BARANGAY_HELP_HTML = "<h1 id=\"notice-title\">Find Your Item</h1>\n<p id=\"notice-body\">Click element to view</p>";

/* dom-topic: change-text */
const SARI_SARI_HTML = "<h1 id=\"notice-title\">Welcome!</h1>\n<p id=\"notice-body\">How can I assist you today?</p>";

/* dom-topic: click-handler */
const PALENGKE_STALL_HTML = "<button id=\"action\">Click Me!</button>\n<p id=\"status\">Welcome to Palengke!</p>";

/* dom-topic: toggle-class */
const JEEPNEY_TERMINAL_HTML = "<button id=\"action\">Change View</button>\n<p id=\"status\">Welcome to the jeepney terminal</p>";

/* dom-topic: read-input */
const TURO_TURO_HTML = "<label for=\"who\">Name Box</label>\n<input id=\"who\" value=\"\">\n<p id=\"greeting\"></p>";

/* dom-topic: create-element */
const BARANGAY_HEALTH_HTML = "<h2 id=\"list-title\">Add Item</h2>\n<ul id=\"items\"></ul>\n<p id=\"count\"></p>";

/* dom-topic: remove-element */
const SCHOOL_REGISTRATION_HTML = "<button id=\"action\">Cancel</button>\n<p id=\"status\">Confirm registration</p>";

/* dom-topic: change-style */
const TRICYCLE_QUEUE_HTML = "<h1 id=\"notice-title\">Screen Update</h1>\n<p id=\"notice-body\">Please wait in line.</p>";

/* dom-topic: find-element */
const BAKERY_COUNTER_HTML = "<h1 id=\"notice-title\">Welcome to Sweet Bakery</h1>\n<p id=\"notice-body\">Click on the item you want</p>";

/* dom-topic: change-text */
const WATER_REFILL_HTML = "<h1 id=\"notice-title\">Water Refill Notice</h1>\n<p id=\"notice-body\">Please check your refill amount.</p>";

/* dom-topic: click-handler */
const BARANGAY_CLEAN_HTML = "<button id=\"action\">Clean Up Now!</button>\n<p id=\"status\">Join the drive for cleaner neighborhoods.</p>";

/* dom-topic: toggle-class */
const COMPUTER_SHOP_HTML = "<button id=\"action\">Click Me!</button>\n<p id=\"status\">Welcome to our computer shop</p>";

/* dom-topic: read-input */
const FIESTA_COMMITTEE_HTML = "<label for=\"who\">Name:</label>\n<input id=\"who\" value=\"\">\n<p id=\"greeting\"></p>";

/* dom-topic: create-element */
const RICE_RETAILER_HTML = "<h2 id=\"list-title\">Add Rice</h2>\n<ul id=\"items\"></ul>\n<p id=\"count\"></p>";

/** Authored proof for every step. Missing entries stop the course from loading. */
const references = {
  "barangay-help-1": { estimatedMinutes: 4, solution: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\n") },
  "barangay-help-2": { estimatedMinutes: 4, solution: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\n") },
  "barangay-help-3": { estimatedMinutes: 4, solution: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\n") },
  "barangay-help-4": { estimatedMinutes: 4, solution: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\n") },
  "barangay-help-5": { estimatedMinutes: 4, solution: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"Please read the notice above.\";\n") },
  "sari-sari-1": { estimatedMinutes: 4, solution: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\n") },
  "sari-sari-2": { estimatedMinutes: 4, solution: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\n") },
  "sari-sari-3": { estimatedMinutes: 4, solution: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\n") },
  "sari-sari-4": { estimatedMinutes: 4, solution: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"How can I assist you today? Thank you.\";\n") },
  "sari-sari-5": { estimatedMinutes: 4, solution: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"How can I assist you today? Thank you.\";\ntitle.setAttribute(\"lang\", \"en\");\n") },
  "palengke-stall-1": { estimatedMinutes: 4, solution: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\n") },
  "palengke-stall-2": { estimatedMinutes: 4, solution: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\n") },
  "palengke-stall-3": { estimatedMinutes: 4, solution: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\n") },
  "palengke-stall-4": { estimatedMinutes: 4, solution: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\n") },
  "palengke-stall-5": { estimatedMinutes: 4, solution: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\nstatus.setAttribute(\"role\", \"status\");\n") },
  "jeepney-terminal-1": { estimatedMinutes: 4, solution: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\n") },
  "jeepney-terminal-2": { estimatedMinutes: 4, solution: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\n") },
  "jeepney-terminal-3": { estimatedMinutes: 4, solution: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\n") },
  "jeepney-terminal-4": { estimatedMinutes: 4, solution: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\n") },
  "jeepney-terminal-5": { estimatedMinutes: 4, solution: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\nbutton.setAttribute(\"aria-pressed\", \"false\");\n") },
  "turo-turo-1": { estimatedMinutes: 4, solution: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\n") },
  "turo-turo-2": { estimatedMinutes: 4, solution: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\n") },
  "turo-turo-3": { estimatedMinutes: 4, solution: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\n") },
  "turo-turo-4": { estimatedMinutes: 4, solution: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\n") },
  "turo-turo-5": { estimatedMinutes: 4, solution: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\ngreeting.setAttribute(\"aria-live\", \"polite\");\n") },
  "barangay-health-1": { estimatedMinutes: 4, solution: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\n") },
  "barangay-health-2": { estimatedMinutes: 4, solution: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\n") },
  "barangay-health-3": { estimatedMinutes: 4, solution: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"Name\";\n") },
  "barangay-health-4": { estimatedMinutes: 4, solution: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"Name\";\nlist.appendChild(item);\n") },
  "barangay-health-5": { estimatedMinutes: 4, solution: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"Name\";\nlist.appendChild(item);\ndocument.querySelector(\"#count\").textContent = list.children.length + \" item\";\n") },
  "school-registration-1": { estimatedMinutes: 4, solution: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\n") },
  "school-registration-2": { estimatedMinutes: 4, solution: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\n") },
  "school-registration-3": { estimatedMinutes: 4, solution: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"dismissible\");\n") },
  "school-registration-4": { estimatedMinutes: 4, solution: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"dismissible\");\nbutton.addEventListener(\"click\", function () {\n  button.textContent = \"Dismissed\";\n});\n") },
  "school-registration-5": { estimatedMinutes: 4, solution: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"dismissible\");\nbutton.addEventListener(\"click\", function () {\n  button.textContent = \"Dismissed\";\n});\nbutton.setAttribute(\"aria-label\", \"Dismiss this notice\");\n") },
  "tricycle-queue-1": { estimatedMinutes: 4, solution: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\n") },
  "tricycle-queue-2": { estimatedMinutes: 4, solution: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\n") },
  "tricycle-queue-3": { estimatedMinutes: 4, solution: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = document.querySelector(\"#notice-body\");\n") },
  "tricycle-queue-4": { estimatedMinutes: 4, solution: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = document.querySelector(\"#notice-body\");\nbody.classList.add(\"muted\");\n") },
  "tricycle-queue-5": { estimatedMinutes: 4, solution: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = document.querySelector(\"#notice-body\");\nbody.classList.add(\"muted\");\ntitle.classList.remove(\"urgent\");\n") },
  "bakery-counter-1": { estimatedMinutes: 4, solution: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\n") },
  "bakery-counter-2": { estimatedMinutes: 4, solution: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\n") },
  "bakery-counter-3": { estimatedMinutes: 4, solution: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\n") },
  "bakery-counter-4": { estimatedMinutes: 4, solution: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\n") },
  "bakery-counter-5": { estimatedMinutes: 4, solution: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"Please read the notice above.\";\n") },
  "water-refill-1": { estimatedMinutes: 4, solution: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\n") },
  "water-refill-2": { estimatedMinutes: 4, solution: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\n") },
  "water-refill-3": { estimatedMinutes: 4, solution: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\n") },
  "water-refill-4": { estimatedMinutes: 4, solution: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"Please check your refill amount. Thank you.\";\n") },
  "water-refill-5": { estimatedMinutes: 4, solution: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"Please check your refill amount. Thank you.\";\ntitle.setAttribute(\"lang\", \"en\");\n") },
  "barangay-clean-1": { estimatedMinutes: 4, solution: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\n") },
  "barangay-clean-2": { estimatedMinutes: 4, solution: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\n") },
  "barangay-clean-3": { estimatedMinutes: 4, solution: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\n") },
  "barangay-clean-4": { estimatedMinutes: 4, solution: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\n") },
  "barangay-clean-5": { estimatedMinutes: 4, solution: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\nstatus.setAttribute(\"role\", \"status\");\n") },
  "computer-shop-1": { estimatedMinutes: 4, solution: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\n") },
  "computer-shop-2": { estimatedMinutes: 4, solution: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\n") },
  "computer-shop-3": { estimatedMinutes: 4, solution: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\n") },
  "computer-shop-4": { estimatedMinutes: 4, solution: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\n") },
  "computer-shop-5": { estimatedMinutes: 4, solution: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\nbutton.setAttribute(\"aria-pressed\", \"false\");\n") },
  "fiesta-committee-1": { estimatedMinutes: 4, solution: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\n") },
  "fiesta-committee-2": { estimatedMinutes: 4, solution: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\n") },
  "fiesta-committee-3": { estimatedMinutes: 4, solution: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\n") },
  "fiesta-committee-4": { estimatedMinutes: 4, solution: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\n") },
  "fiesta-committee-5": { estimatedMinutes: 4, solution: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\ngreeting.setAttribute(\"aria-live\", \"polite\");\n") },
  "rice-retailer-1": { estimatedMinutes: 4, solution: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\n") },
  "rice-retailer-2": { estimatedMinutes: 4, solution: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\n") },
  "rice-retailer-3": { estimatedMinutes: 4, solution: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"5KG Bag\";\n") },
  "rice-retailer-4": { estimatedMinutes: 4, solution: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"5KG Bag\";\nlist.appendChild(item);\n") },
  "rice-retailer-5": { estimatedMinutes: 4, solution: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"5KG Bag\";\nlist.appendChild(item);\ndocument.querySelector(\"#count\").textContent = list.children.length + \" item\";\n") },
} satisfies Record<string, StepReference>;
const PROJECT_1_ID = "barangay-help";
const s1 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_1_ID }; };

const PROJECT_2_ID = "sari-sari";
const s2 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_2_ID }; };

const PROJECT_3_ID = "palengke-stall";
const s3 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_3_ID }; };

const PROJECT_4_ID = "jeepney-terminal";
const s4 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_4_ID }; };

const PROJECT_5_ID = "turo-turo";
const s5 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_5_ID }; };

const PROJECT_6_ID = "barangay-health";
const s6 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_6_ID }; };

const PROJECT_7_ID = "school-registration";
const s7 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_7_ID }; };

const PROJECT_8_ID = "tricycle-queue";
const s8 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_8_ID }; };

const PROJECT_9_ID = "bakery-counter";
const s9 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_9_ID }; };

const PROJECT_10_ID = "water-refill";
const s10 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_10_ID }; };

const PROJECT_11_ID = "barangay-clean";
const s11 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_11_ID }; };

const PROJECT_12_ID = "computer-shop";
const s12 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_12_ID }; };

const PROJECT_13_ID = "fiesta-committee";
const s13 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_13_ID }; };

const PROJECT_14_ID = "rice-retailer";
const s14 = (step: Omit<Step, "index" | "kind" | "projectId">): Step => { const reference = references[step.id as keyof typeof references]; if (!reference) throw new Error(`Missing reference data for DOM step: ${step.id}`); return { ...step, ...reference, index: ++n, kind: "web", projectId: PROJECT_14_ID }; };


export const domCourse: Course = {
  id: "dom-basics",
  order: 5,
  title: "Learn JavaScript on a Page by Building Barangay Screens",
  project: "Barangay Notice",
  projects: [ { id: PROJECT_1_ID, title: "Barangay Help" }, { id: PROJECT_2_ID, title: "Sari Sari" }, { id: PROJECT_3_ID, title: "Palengke Stall" }, { id: PROJECT_4_ID, title: "Jeepney Terminal" }, { id: PROJECT_5_ID, title: "Turo Turo" }, { id: PROJECT_6_ID, title: "Barangay Health" }, { id: PROJECT_7_ID, title: "School Registration" }, { id: PROJECT_8_ID, title: "Tricycle Queue" }, { id: PROJECT_9_ID, title: "Bakery Counter" }, { id: PROJECT_10_ID, title: "Water Refill" }, { id: PROJECT_11_ID, title: "Barangay Clean" }, { id: PROJECT_12_ID, title: "Computer Shop" }, { id: PROJECT_13_ID, title: "Fiesta Committee" }, { id: PROJECT_14_ID, title: "Rice Retailer" } ],
  kind: "web",
  requires: ["js-basics"],
  summary:
    "Make a real page answer back. Find the parts of a page from your script, change what they say, and run your own code when somebody clicks.",
  steps: [
    s1({ id: "barangay-help-1", task: "Find the heading so the script can work with it.", inputMode: "guided", files: page(BARANGAY_HELP_HTML, "const title = document.querySelector();;\n"), activeFile: "script.js", highlightToken: "const title = document.querySelector();;", tests: [{ id: "barangay-help-1-check", label: "#notice-title reads Find Your Item", kind: "page-text-equals", selector: "#notice-title", value: "Find Your Item" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-title\") after the equals sign." }], xp: 50 }),
    s1({ id: "barangay-help-2", task: "Read the words that are already in the heading.", inputMode: "guided", files: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = ;\n"), activeFile: "script.js", highlightToken: "const words = ;", tests: [{ id: "barangay-help-2-check", label: "#notice-title reads Find Your Item", kind: "page-text-equals", selector: "#notice-title", value: "Find Your Item" }], hints: [{ level: 1, text: "An element keeps its words in a property." }, { level: 2, text: "Write title.textContent after the equals sign." }], xp: 50 }),
    s1({ id: "barangay-help-3", task: "Add the word updated to the end of the heading.", inputMode: "guided", files: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = ;\n"), activeFile: "script.js", highlightToken: "title.textContent = ;", tests: [{ id: "barangay-help-3-check", label: "#notice-title reads Find Your Item (updated)", kind: "page-text-equals", selector: "#notice-title", value: "Find Your Item (updated)" }], hints: [{ level: 1, text: "Join the words you read to the new part." }, { level: 2, text: "Write words + \" (updated)\" after the equals sign." }], xp: 50 }),
    s1({ id: "barangay-help-4", task: "Find the message below the heading.", inputMode: "guided", files: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = ;\n"), activeFile: "script.js", highlightToken: "const body = ;", tests: [{ id: "barangay-help-4-check", label: "#notice-body reads Click element to view", kind: "page-text-equals", selector: "#notice-body", value: "Click element to view" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-body\") after the equals sign." }], xp: 50 }),
    s1({ id: "barangay-help-5", task: "Replace the message with a line pointing at the heading.", inputMode: "guided", files: page(BARANGAY_HELP_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = ;\n"), activeFile: "script.js", highlightToken: "body.textContent = ;", tests: [{ id: "barangay-help-5-check", label: "#notice-body reads Please read the notice above.", kind: "page-text-equals", selector: "#notice-body", value: "Please read the notice above." }], hints: [{ level: 1, text: "Put the new words in quotes." }, { level: 2, text: "Write \"Please read the notice above.\" after the equals sign." }], xp: 50 }),
    s2({ id: "sari-sari-1", task: "Find the heading.", inputMode: "guided", files: page(SARI_SARI_HTML, "const title = ;\n"), activeFile: "script.js", highlightToken: "const title = ;", tests: [{ id: "sari-sari-1-check", label: "#notice-title reads Welcome!", kind: "page-text-equals", selector: "#notice-title", value: "Welcome!" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-title\") after the equals sign." }], xp: 50 }),
    s2({ id: "sari-sari-2", task: "Change the heading to say Today's Notice.", inputMode: "guided", files: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = ;\n"), activeFile: "script.js", highlightToken: "title.textContent = ;", tests: [{ id: "sari-sari-2-check", label: "#notice-title reads Today's Notice", kind: "page-text-equals", selector: "#notice-title", value: "Today's Notice" }], hints: [{ level: 1, text: "Put the new words in quotes." }, { level: 2, text: "Write \"Today's Notice\" after the equals sign." }], xp: 50 }),
    s2({ id: "sari-sari-3", task: "Find the message.", inputMode: "guided", files: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = ;\n"), activeFile: "script.js", highlightToken: "const body = ;", tests: [{ id: "sari-sari-3-check", label: "#notice-body reads How can I assist you today?", kind: "page-text-equals", selector: "#notice-body", value: "How can I assist you today?" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-body\") after the equals sign." }], xp: 50 }),
    s2({ id: "sari-sari-4", task: "Add a thank you to the end of the message.", inputMode: "guided", files: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = ;\n"), activeFile: "script.js", highlightToken: "body.textContent = ;", tests: [{ id: "sari-sari-4-check", label: "#notice-body reads How can I assist you today? Thank you.", kind: "page-text-equals", selector: "#notice-body", value: "How can I assist you today? Thank you." }], hints: [{ level: 1, text: "Put the whole new sentence in quotes." }, { level: 2, text: "Write \"How can I assist you today? Thank you.\" after the equals sign." }], xp: 50 }),
    s2({ id: "sari-sari-5", task: "Mark the heading as English so screen readers say it correctly.", inputMode: "guided", files: page(SARI_SARI_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"How can I assist you today? Thank you.\";\ntitle.setAttribute(\"lang\", );\n"), activeFile: "script.js", highlightToken: "title.setAttribute(\"lang\", );", tests: [{ id: "sari-sari-5-check", label: "#notice-title has lang set to en", kind: "page-attr-equals", selector: "#notice-title", attr: "lang", value: "en" }], hints: [{ level: 1, text: "The language code goes in quotes as the second value." }, { level: 2, text: "Write \"en\" as the second value." }], xp: 50 }),
    s3({ id: "palengke-stall-1", task: "Find the button.", inputMode: "guided", files: page(PALENGKE_STALL_HTML, "const button = ;\n"), activeFile: "script.js", highlightToken: "const button = ;", tests: [{ id: "palengke-stall-1-check", label: "#action reads Click Me!", kind: "page-text-equals", selector: "#action", value: "Click Me!" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#action\") after the equals sign." }], xp: 50 }),
    s3({ id: "palengke-stall-2", task: "Find the line the page shows.", inputMode: "guided", files: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = ;\n"), activeFile: "script.js", highlightToken: "const status = ;", tests: [{ id: "palengke-stall-2-check", label: "#status reads Welcome to Palengke!", kind: "page-text-equals", selector: "#status", value: "Welcome to Palengke!" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#status\") after the equals sign." }], xp: 50 }),
    s3({ id: "palengke-stall-3", task: "Make the line say Done when the button is pressed.", inputMode: "guided", files: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(, function () {\n  status.textContent = \"Done\";\n});\n"), activeFile: "script.js", highlightToken: "addEventListener(,", tests: [{ id: "palengke-stall-3-check", label: "#status reads Done after the click", kind: "page-click-text-equals", clickSelector: "#action", selector: "#status", value: "Done" }], hints: [{ level: 1, text: "Name the event you are listening for, in quotes." }, { level: 2, text: "Write \"click\" as the first value." }], xp: 50 }),
    s3({ id: "palengke-stall-4", task: "Say plainly that this button does not submit a form.", inputMode: "guided", files: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", );\n"), activeFile: "script.js", highlightToken: "button.setAttribute(\"type\", );", tests: [{ id: "palengke-stall-4-check", label: "#action has type set to button", kind: "page-attr-equals", selector: "#action", attr: "type", value: "button" }], hints: [{ level: 1, text: "The type goes in quotes as the second value." }, { level: 2, text: "Write \"button\" as the second value." }], xp: 50 }),
    s3({ id: "palengke-stall-5", task: "Let a screen reader announce the line when it changes.", inputMode: "guided", files: page(PALENGKE_STALL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\nstatus.setAttribute(\"role\", );\n"), activeFile: "script.js", highlightToken: "status.setAttribute(\"role\", );", tests: [{ id: "palengke-stall-5-check", label: "#status has role set to status", kind: "page-attr-equals", selector: "#status", attr: "role", value: "status" }], hints: [{ level: 1, text: "The role name goes in quotes as the second value." }, { level: 2, text: "Write \"status\" as the second value." }], xp: 50 }),
    s4({ id: "jeepney-terminal-1", task: "Find the button.", inputMode: "guided", files: page(JEEPNEY_TERMINAL_HTML, "const button = ;\n"), activeFile: "script.js", highlightToken: "const button = ;", tests: [{ id: "jeepney-terminal-1-check", label: "#action reads Change View", kind: "page-text-equals", selector: "#action", value: "Change View" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#action\") after the equals sign." }], xp: 50 }),
    s4({ id: "jeepney-terminal-2", task: "Find the line the page shows.", inputMode: "guided", files: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = ;\n"), activeFile: "script.js", highlightToken: "const status = ;", tests: [{ id: "jeepney-terminal-2-check", label: "#status reads Welcome to the jeepney terminal", kind: "page-text-equals", selector: "#status", value: "Welcome to the jeepney terminal" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#status\") after the equals sign." }], xp: 50 }),
    s4({ id: "jeepney-terminal-3", task: "Give the line a starting class of resting.", inputMode: "guided", files: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add();\n"), activeFile: "script.js", highlightToken: "classList.add();", tests: [{ id: "jeepney-terminal-3-check", label: "#status carries the class resting", kind: "page-class-contains", selector: "#status", value: "resting" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"resting\" inside the brackets." }], xp: 50 }),
    s4({ id: "jeepney-terminal-4", task: "Add the class active when the button is pressed, and take it off when pressed again.", inputMode: "guided", files: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle();\n});\n"), activeFile: "script.js", highlightToken: "classList.toggle();", tests: [{ id: "jeepney-terminal-4-check", label: "#status carries the class active after the click", kind: "page-click-class-contains", clickSelector: "#action", selector: "#status", value: "active" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"active\" inside the brackets." }], xp: 50 }),
    s4({ id: "jeepney-terminal-5", task: "Say that the button starts in its off position.", inputMode: "guided", files: page(JEEPNEY_TERMINAL_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\nbutton.setAttribute(\"aria-pressed\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"aria-pressed\", );", tests: [{ id: "jeepney-terminal-5-check", label: "#action has aria-pressed set to false", kind: "page-attr-equals", selector: "#action", attr: "aria-pressed", value: "false" }], hints: [{ level: 1, text: "The starting answer goes in quotes as the second value." }, { level: 2, text: "Write \"false\" as the second value." }], xp: 50 }),
    s5({ id: "turo-turo-1", task: "Find the name box.", inputMode: "guided", files: page(TURO_TURO_HTML, "const field = ;\n"), activeFile: "script.js", highlightToken: "const field = ;", tests: [{ id: "turo-turo-1-check", label: "#who is on the page", kind: "page-exists", selector: "#who" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#who\") after the equals sign." }], xp: 50 }),
    s5({ id: "turo-turo-2", task: "Find the line where the greeting will go.", inputMode: "guided", files: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = ;\n"), activeFile: "script.js", highlightToken: "const greeting = ;", tests: [{ id: "turo-turo-2-check", label: "#greeting is on the page", kind: "page-exists", selector: "#greeting" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#greeting\") after the equals sign." }], xp: 50 }),
    s5({ id: "turo-turo-3", task: "Greet whoever is typing, as they type.", inputMode: "guided", files: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = ;\n});\n"), activeFile: "script.js", highlightToken: "greeting.textContent = ;", tests: [{ id: "turo-turo-3-check", label: "#greeting reads Hello, Juan once Juan is typed", kind: "page-input-text-equals", selector: "#greeting", type: "Juan", value: "Hello, Juan" }], hints: [{ level: 1, text: "A box keeps what was typed in its value property." }, { level: 2, text: "Write \"Hello, \" + field.value after the equals sign." }], xp: 50 }),
    s5({ id: "turo-turo-4", task: "Show a hint inside the empty box.", inputMode: "guided", files: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"placeholder\", );", tests: [{ id: "turo-turo-4-check", label: "#who has placeholder set to Your name", kind: "page-attr-equals", selector: "#who", attr: "placeholder", value: "Your name" }], hints: [{ level: 1, text: "The hint goes in quotes as the second value." }, { level: 2, text: "Write \"Your name\" as the second value." }], xp: 50 }),
    s5({ id: "turo-turo-5", task: "Let a screen reader read the greeting without interrupting.", inputMode: "guided", files: page(TURO_TURO_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\ngreeting.setAttribute(\"aria-live\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"aria-live\", );", tests: [{ id: "turo-turo-5-check", label: "#greeting has aria-live set to polite", kind: "page-attr-equals", selector: "#greeting", attr: "aria-live", value: "polite" }], hints: [{ level: 1, text: "The politeness setting goes in quotes as the second value." }, { level: 2, text: "Write \"polite\" as the second value." }], xp: 50 }),
    s6({ id: "barangay-health-1", task: "Find the empty list.", inputMode: "guided", files: page(BARANGAY_HEALTH_HTML, "const list = ;\n"), activeFile: "script.js", highlightToken: "const list = ;", tests: [{ id: "barangay-health-1-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#items\") after the equals sign." }], xp: 50 }),
    s6({ id: "barangay-health-2", task: "Make a new list item, not yet on the page.", inputMode: "guided", files: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement();;\n"), activeFile: "script.js", highlightToken: "const item = document.createElement();;", tests: [{ id: "barangay-health-2-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "The tag name goes in quotes inside the brackets." }, { level: 2, text: "Write document.createElement(\"li\") after the equals sign." }], xp: 50 }),
    s6({ id: "barangay-health-3", task: "Put the words into the new item.", inputMode: "guided", files: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = ;\n"), activeFile: "script.js", highlightToken: "item.textContent = ;", tests: [{ id: "barangay-health-3-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "Put the words in quotes." }, { level: 2, text: "Write \"Name\" after the equals sign." }], xp: 50 }),
    s6({ id: "barangay-health-4", task: "Put the new item onto the page, inside the list.", inputMode: "guided", files: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"Name\";\nlist.appendChild();\n"), activeFile: "script.js", highlightToken: "appendChild();", tests: [{ id: "barangay-health-4-check", label: "#items li reads Name", kind: "page-text-equals", selector: "#items li", value: "Name" }], hints: [{ level: 1, text: "Name the element you are adding." }, { level: 2, text: "Write item inside the brackets." }], xp: 50 }),
    s6({ id: "barangay-health-5", task: "Show how many items the list now holds.", inputMode: "guided", files: page(BARANGAY_HEALTH_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"Name\";\nlist.appendChild(item);\ndocument.querySelector(\"#count\").textContent = ;\n"), activeFile: "script.js", highlightToken: "\"#count\").textContent = ;", tests: [{ id: "barangay-health-5-check", label: "#count reads 1 item", kind: "page-text-equals", selector: "#count", value: "1 item" }], hints: [{ level: 1, text: "A list reports how many children it has." }, { level: 2, text: "Write list.children.length + \" item\" after the equals sign." }], xp: 50 }),
    s7({ id: "school-registration-1", task: "Find the button.", inputMode: "guided", files: page(SCHOOL_REGISTRATION_HTML, "const button = ;\n"), activeFile: "script.js", highlightToken: "const button = ;", tests: [{ id: "school-registration-1-check", label: "#action reads Cancel", kind: "page-text-equals", selector: "#action", value: "Cancel" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#action\") after the equals sign." }], xp: 50 }),
    s7({ id: "school-registration-2", task: "Find the line the page shows.", inputMode: "guided", files: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = ;\n"), activeFile: "script.js", highlightToken: "const status = ;", tests: [{ id: "school-registration-2-check", label: "#status reads Confirm registration", kind: "page-text-equals", selector: "#status", value: "Confirm registration" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#status\") after the equals sign." }], xp: 50 }),
    s7({ id: "school-registration-3", task: "Mark the line as one that can be dismissed.", inputMode: "guided", files: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add();\n"), activeFile: "script.js", highlightToken: "classList.add();", tests: [{ id: "school-registration-3-check", label: "#status carries the class dismissible", kind: "page-class-contains", selector: "#status", value: "dismissible" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"dismissible\" inside the brackets." }], xp: 50 }),
    s7({ id: "school-registration-4", task: "Make the button say Dismissed once it has been pressed.", inputMode: "guided", files: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"dismissible\");\nbutton.addEventListener(\"click\", function () {\n  button.textContent = ;\n});\n"), activeFile: "script.js", highlightToken: "button.textContent = ;", tests: [{ id: "school-registration-4-check", label: "#action reads Dismissed after the click", kind: "page-click-text-equals", clickSelector: "#action", selector: "#action", value: "Dismissed" }], hints: [{ level: 1, text: "Put the new word in quotes." }, { level: 2, text: "Write \"Dismissed\" after the equals sign." }], xp: 50 }),
    s7({ id: "school-registration-5", task: "Give the button a fuller name for screen readers.", inputMode: "guided", files: page(SCHOOL_REGISTRATION_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"dismissible\");\nbutton.addEventListener(\"click\", function () {\n  button.textContent = \"Dismissed\";\n});\nbutton.setAttribute(\"aria-label\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"aria-label\", );", tests: [{ id: "school-registration-5-check", label: "#action has aria-label set to Dismiss this notice", kind: "page-attr-equals", selector: "#action", attr: "aria-label", value: "Dismiss this notice" }], hints: [{ level: 1, text: "The fuller name goes in quotes as the second value." }, { level: 2, text: "Write \"Dismiss this notice\" as the second value." }], xp: 50 }),
    s8({ id: "tricycle-queue-1", task: "Find the heading.", inputMode: "guided", files: page(TRICYCLE_QUEUE_HTML, "const title = ;\n"), activeFile: "script.js", highlightToken: "const title = ;", tests: [{ id: "tricycle-queue-1-check", label: "#notice-title reads Screen Update", kind: "page-text-equals", selector: "#notice-title", value: "Screen Update" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-title\") after the equals sign." }], xp: 50 }),
    s8({ id: "tricycle-queue-2", task: "Mark the heading as urgent, so CSS can style it.", inputMode: "guided", files: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add();\n"), activeFile: "script.js", highlightToken: "classList.add();", tests: [{ id: "tricycle-queue-2-check", label: "#notice-title carries the class urgent", kind: "page-class-contains", selector: "#notice-title", value: "urgent" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"urgent\" inside the brackets." }], xp: 50 }),
    s8({ id: "tricycle-queue-3", task: "Find the message.", inputMode: "guided", files: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = ;\n"), activeFile: "script.js", highlightToken: "const body = ;", tests: [{ id: "tricycle-queue-3-check", label: "#notice-body reads Please wait in line.", kind: "page-text-equals", selector: "#notice-body", value: "Please wait in line." }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-body\") after the equals sign." }], xp: 50 }),
    s8({ id: "tricycle-queue-4", task: "Mark the message as the quieter part.", inputMode: "guided", files: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = document.querySelector(\"#notice-body\");\nbody.classList.add();\n"), activeFile: "script.js", highlightToken: "classList.add();", tests: [{ id: "tricycle-queue-4-check", label: "#notice-body carries the class muted", kind: "page-class-contains", selector: "#notice-body", value: "muted" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"muted\" inside the brackets." }], xp: 50 }),
    s8({ id: "tricycle-queue-5", task: "Take the urgent mark back off the heading.", inputMode: "guided", files: page(TRICYCLE_QUEUE_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.classList.add(\"urgent\");\nconst body = document.querySelector(\"#notice-body\");\nbody.classList.add(\"muted\");\ntitle.classList.remove();\n"), activeFile: "script.js", highlightToken: "classList.remove();", tests: [{ id: "tricycle-queue-5-check", label: "#notice-title is on the page", kind: "page-exists", selector: "#notice-title" }], hints: [{ level: 1, text: "Name the class you are taking away." }, { level: 2, text: "Write \"urgent\" inside the brackets." }], xp: 50 }),
    s9({ id: "bakery-counter-1", task: "Find the heading so the script can work with it.", inputMode: "guided", files: page(BAKERY_COUNTER_HTML, "const title = document.querySelector();;\n"), activeFile: "script.js", highlightToken: "const title = document.querySelector();;", tests: [{ id: "bakery-counter-1-check", label: "#notice-title reads Welcome to Sweet Bakery", kind: "page-text-equals", selector: "#notice-title", value: "Welcome to Sweet Bakery" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-title\") after the equals sign." }], xp: 50 }),
    s9({ id: "bakery-counter-2", task: "Read the words that are already in the heading.", inputMode: "guided", files: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = ;\n"), activeFile: "script.js", highlightToken: "const words = ;", tests: [{ id: "bakery-counter-2-check", label: "#notice-title reads Welcome to Sweet Bakery", kind: "page-text-equals", selector: "#notice-title", value: "Welcome to Sweet Bakery" }], hints: [{ level: 1, text: "An element keeps its words in a property." }, { level: 2, text: "Write title.textContent after the equals sign." }], xp: 50 }),
    s9({ id: "bakery-counter-3", task: "Add the word updated to the end of the heading.", inputMode: "guided", files: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = ;\n"), activeFile: "script.js", highlightToken: "title.textContent = ;", tests: [{ id: "bakery-counter-3-check", label: "#notice-title reads Welcome to Sweet Bakery (updated)", kind: "page-text-equals", selector: "#notice-title", value: "Welcome to Sweet Bakery (updated)" }], hints: [{ level: 1, text: "Join the words you read to the new part." }, { level: 2, text: "Write words + \" (updated)\" after the equals sign." }], xp: 50 }),
    s9({ id: "bakery-counter-4", task: "Find the message below the heading.", inputMode: "guided", files: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = ;\n"), activeFile: "script.js", highlightToken: "const body = ;", tests: [{ id: "bakery-counter-4-check", label: "#notice-body reads Click on the item you want", kind: "page-text-equals", selector: "#notice-body", value: "Click on the item you want" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-body\") after the equals sign." }], xp: 50 }),
    s9({ id: "bakery-counter-5", task: "Replace the message with a line pointing at the heading.", inputMode: "guided", files: page(BAKERY_COUNTER_HTML, "const title = document.querySelector(\"#notice-title\");\nconst words = title.textContent;\ntitle.textContent = words + \" (updated)\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = ;\n"), activeFile: "script.js", highlightToken: "body.textContent = ;", tests: [{ id: "bakery-counter-5-check", label: "#notice-body reads Please read the notice above.", kind: "page-text-equals", selector: "#notice-body", value: "Please read the notice above." }], hints: [{ level: 1, text: "Put the new words in quotes." }, { level: 2, text: "Write \"Please read the notice above.\" after the equals sign." }], xp: 50 }),
    s10({ id: "water-refill-1", task: "Find the heading.", inputMode: "guided", files: page(WATER_REFILL_HTML, "const title = ;\n"), activeFile: "script.js", highlightToken: "const title = ;", tests: [{ id: "water-refill-1-check", label: "#notice-title reads Water Refill Notice", kind: "page-text-equals", selector: "#notice-title", value: "Water Refill Notice" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-title\") after the equals sign." }], xp: 50 }),
    s10({ id: "water-refill-2", task: "Change the heading to say Today's Notice.", inputMode: "guided", files: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = ;\n"), activeFile: "script.js", highlightToken: "title.textContent = ;", tests: [{ id: "water-refill-2-check", label: "#notice-title reads Today's Notice", kind: "page-text-equals", selector: "#notice-title", value: "Today's Notice" }], hints: [{ level: 1, text: "Put the new words in quotes." }, { level: 2, text: "Write \"Today's Notice\" after the equals sign." }], xp: 50 }),
    s10({ id: "water-refill-3", task: "Find the message.", inputMode: "guided", files: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = ;\n"), activeFile: "script.js", highlightToken: "const body = ;", tests: [{ id: "water-refill-3-check", label: "#notice-body reads Please check your refill amount.", kind: "page-text-equals", selector: "#notice-body", value: "Please check your refill amount." }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#notice-body\") after the equals sign." }], xp: 50 }),
    s10({ id: "water-refill-4", task: "Add a thank you to the end of the message.", inputMode: "guided", files: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = ;\n"), activeFile: "script.js", highlightToken: "body.textContent = ;", tests: [{ id: "water-refill-4-check", label: "#notice-body reads Please check your refill amount. Thank you.", kind: "page-text-equals", selector: "#notice-body", value: "Please check your refill amount. Thank you." }], hints: [{ level: 1, text: "Put the whole new sentence in quotes." }, { level: 2, text: "Write \"Please check your refill amount. Thank you.\" after the equals sign." }], xp: 50 }),
    s10({ id: "water-refill-5", task: "Mark the heading as English so screen readers say it correctly.", inputMode: "guided", files: page(WATER_REFILL_HTML, "const title = document.querySelector(\"#notice-title\");\ntitle.textContent = \"Today's Notice\";\nconst body = document.querySelector(\"#notice-body\");\nbody.textContent = \"Please check your refill amount. Thank you.\";\ntitle.setAttribute(\"lang\", );\n"), activeFile: "script.js", highlightToken: "title.setAttribute(\"lang\", );", tests: [{ id: "water-refill-5-check", label: "#notice-title has lang set to en", kind: "page-attr-equals", selector: "#notice-title", attr: "lang", value: "en" }], hints: [{ level: 1, text: "The language code goes in quotes as the second value." }, { level: 2, text: "Write \"en\" as the second value." }], xp: 50 }),
    s11({ id: "barangay-clean-1", task: "Find the button.", inputMode: "guided", files: page(BARANGAY_CLEAN_HTML, "const button = ;\n"), activeFile: "script.js", highlightToken: "const button = ;", tests: [{ id: "barangay-clean-1-check", label: "#action reads Clean Up Now!", kind: "page-text-equals", selector: "#action", value: "Clean Up Now!" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#action\") after the equals sign." }], xp: 50 }),
    s11({ id: "barangay-clean-2", task: "Find the line the page shows.", inputMode: "guided", files: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = ;\n"), activeFile: "script.js", highlightToken: "const status = ;", tests: [{ id: "barangay-clean-2-check", label: "#status reads Join the drive for cleaner neighborhoods.", kind: "page-text-equals", selector: "#status", value: "Join the drive for cleaner neighborhoods." }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#status\") after the equals sign." }], xp: 50 }),
    s11({ id: "barangay-clean-3", task: "Make the line say Done when the button is pressed.", inputMode: "guided", files: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(, function () {\n  status.textContent = \"Done\";\n});\n"), activeFile: "script.js", highlightToken: "addEventListener(,", tests: [{ id: "barangay-clean-3-check", label: "#status reads Done after the click", kind: "page-click-text-equals", clickSelector: "#action", selector: "#status", value: "Done" }], hints: [{ level: 1, text: "Name the event you are listening for, in quotes." }, { level: 2, text: "Write \"click\" as the first value." }], xp: 50 }),
    s11({ id: "barangay-clean-4", task: "Say plainly that this button does not submit a form.", inputMode: "guided", files: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", );\n"), activeFile: "script.js", highlightToken: "button.setAttribute(\"type\", );", tests: [{ id: "barangay-clean-4-check", label: "#action has type set to button", kind: "page-attr-equals", selector: "#action", attr: "type", value: "button" }], hints: [{ level: 1, text: "The type goes in quotes as the second value." }, { level: 2, text: "Write \"button\" as the second value." }], xp: 50 }),
    s11({ id: "barangay-clean-5", task: "Let a screen reader announce the line when it changes.", inputMode: "guided", files: page(BARANGAY_CLEAN_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", function () {\n  status.textContent = \"Done\";\n});\nbutton.setAttribute(\"type\", \"button\");\nstatus.setAttribute(\"role\", );\n"), activeFile: "script.js", highlightToken: "status.setAttribute(\"role\", );", tests: [{ id: "barangay-clean-5-check", label: "#status has role set to status", kind: "page-attr-equals", selector: "#status", attr: "role", value: "status" }], hints: [{ level: 1, text: "The role name goes in quotes as the second value." }, { level: 2, text: "Write \"status\" as the second value." }], xp: 50 }),
    s12({ id: "computer-shop-1", task: "Find the button.", inputMode: "guided", files: page(COMPUTER_SHOP_HTML, "const button = ;\n"), activeFile: "script.js", highlightToken: "const button = ;", tests: [{ id: "computer-shop-1-check", label: "#action reads Click Me!", kind: "page-text-equals", selector: "#action", value: "Click Me!" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#action\") after the equals sign." }], xp: 50 }),
    s12({ id: "computer-shop-2", task: "Find the line the page shows.", inputMode: "guided", files: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = ;\n"), activeFile: "script.js", highlightToken: "const status = ;", tests: [{ id: "computer-shop-2-check", label: "#status reads Welcome to our computer shop", kind: "page-text-equals", selector: "#status", value: "Welcome to our computer shop" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#status\") after the equals sign." }], xp: 50 }),
    s12({ id: "computer-shop-3", task: "Give the line a starting class of resting.", inputMode: "guided", files: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add();\n"), activeFile: "script.js", highlightToken: "classList.add();", tests: [{ id: "computer-shop-3-check", label: "#status carries the class resting", kind: "page-class-contains", selector: "#status", value: "resting" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"resting\" inside the brackets." }], xp: 50 }),
    s12({ id: "computer-shop-4", task: "Add the class active when the button is pressed, and take it off when pressed again.", inputMode: "guided", files: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle();\n});\n"), activeFile: "script.js", highlightToken: "classList.toggle();", tests: [{ id: "computer-shop-4-check", label: "#status carries the class active after the click", kind: "page-click-class-contains", clickSelector: "#action", selector: "#status", value: "active" }], hints: [{ level: 1, text: "The class name goes in quotes inside the brackets." }, { level: 2, text: "Write \"active\" inside the brackets." }], xp: 50 }),
    s12({ id: "computer-shop-5", task: "Say that the button starts in its off position.", inputMode: "guided", files: page(COMPUTER_SHOP_HTML, "const button = document.querySelector(\"#action\");\nconst status = document.querySelector(\"#status\");\nstatus.classList.add(\"resting\");\nbutton.addEventListener(\"click\", function () {\n  status.classList.toggle(\"active\");\n});\nbutton.setAttribute(\"aria-pressed\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"aria-pressed\", );", tests: [{ id: "computer-shop-5-check", label: "#action has aria-pressed set to false", kind: "page-attr-equals", selector: "#action", attr: "aria-pressed", value: "false" }], hints: [{ level: 1, text: "The starting answer goes in quotes as the second value." }, { level: 2, text: "Write \"false\" as the second value." }], xp: 50 }),
    s13({ id: "fiesta-committee-1", task: "Find the name box.", inputMode: "guided", files: page(FIESTA_COMMITTEE_HTML, "const field = ;\n"), activeFile: "script.js", highlightToken: "const field = ;", tests: [{ id: "fiesta-committee-1-check", label: "#who is on the page", kind: "page-exists", selector: "#who" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#who\") after the equals sign." }], xp: 50 }),
    s13({ id: "fiesta-committee-2", task: "Find the line where the greeting will go.", inputMode: "guided", files: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = ;\n"), activeFile: "script.js", highlightToken: "const greeting = ;", tests: [{ id: "fiesta-committee-2-check", label: "#greeting is on the page", kind: "page-exists", selector: "#greeting" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#greeting\") after the equals sign." }], xp: 50 }),
    s13({ id: "fiesta-committee-3", task: "Greet whoever is typing, as they type.", inputMode: "guided", files: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = ;\n});\n"), activeFile: "script.js", highlightToken: "greeting.textContent = ;", tests: [{ id: "fiesta-committee-3-check", label: "#greeting reads Hello, John once John is typed", kind: "page-input-text-equals", selector: "#greeting", type: "John", value: "Hello, John" }], hints: [{ level: 1, text: "A box keeps what was typed in its value property." }, { level: 2, text: "Write \"Hello, \" + field.value after the equals sign." }], xp: 50 }),
    s13({ id: "fiesta-committee-4", task: "Show a hint inside the empty box.", inputMode: "guided", files: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"placeholder\", );", tests: [{ id: "fiesta-committee-4-check", label: "#who has placeholder set to Your name", kind: "page-attr-equals", selector: "#who", attr: "placeholder", value: "Your name" }], hints: [{ level: 1, text: "The hint goes in quotes as the second value." }, { level: 2, text: "Write \"Your name\" as the second value." }], xp: 50 }),
    s13({ id: "fiesta-committee-5", task: "Let a screen reader read the greeting without interrupting.", inputMode: "guided", files: page(FIESTA_COMMITTEE_HTML, "const field = document.querySelector(\"#who\");\nconst greeting = document.querySelector(\"#greeting\");\nfield.addEventListener(\"input\", function () {\n  greeting.textContent = \"Hello, \" + field.value;\n});\nfield.setAttribute(\"placeholder\", \"Your name\");\ngreeting.setAttribute(\"aria-live\", );\n"), activeFile: "script.js", highlightToken: "setAttribute(\"aria-live\", );", tests: [{ id: "fiesta-committee-5-check", label: "#greeting has aria-live set to polite", kind: "page-attr-equals", selector: "#greeting", attr: "aria-live", value: "polite" }], hints: [{ level: 1, text: "The politeness setting goes in quotes as the second value." }, { level: 2, text: "Write \"polite\" as the second value." }], xp: 50 }),
    s14({ id: "rice-retailer-1", task: "Find the empty list.", inputMode: "guided", files: page(RICE_RETAILER_HTML, "const list = ;\n"), activeFile: "script.js", highlightToken: "const list = ;", tests: [{ id: "rice-retailer-1-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "Ask the document for the element with that id." }, { level: 2, text: "Write document.querySelector(\"#items\") after the equals sign." }], xp: 50 }),
    s14({ id: "rice-retailer-2", task: "Make a new list item, not yet on the page.", inputMode: "guided", files: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement();;\n"), activeFile: "script.js", highlightToken: "const item = document.createElement();;", tests: [{ id: "rice-retailer-2-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "The tag name goes in quotes inside the brackets." }, { level: 2, text: "Write document.createElement(\"li\") after the equals sign." }], xp: 50 }),
    s14({ id: "rice-retailer-3", task: "Put the words into the new item.", inputMode: "guided", files: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = ;\n"), activeFile: "script.js", highlightToken: "item.textContent = ;", tests: [{ id: "rice-retailer-3-check", label: "#items is on the page", kind: "page-exists", selector: "#items" }], hints: [{ level: 1, text: "Put the words in quotes." }, { level: 2, text: "Write \"5KG Bag\" after the equals sign." }], xp: 50 }),
    s14({ id: "rice-retailer-4", task: "Put the new item onto the page, inside the list.", inputMode: "guided", files: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"5KG Bag\";\nlist.appendChild();\n"), activeFile: "script.js", highlightToken: "appendChild();", tests: [{ id: "rice-retailer-4-check", label: "#items li reads 5KG Bag", kind: "page-text-equals", selector: "#items li", value: "5KG Bag" }], hints: [{ level: 1, text: "Name the element you are adding." }, { level: 2, text: "Write item inside the brackets." }], xp: 50 }),
    s14({ id: "rice-retailer-5", task: "Show how many items the list now holds.", inputMode: "guided", files: page(RICE_RETAILER_HTML, "const list = document.querySelector(\"#items\");\nconst item = document.createElement(\"li\");\nitem.textContent = \"5KG Bag\";\nlist.appendChild(item);\ndocument.querySelector(\"#count\").textContent = ;\n"), activeFile: "script.js", highlightToken: "\"#count\").textContent = ;", tests: [{ id: "rice-retailer-5-check", label: "#count reads 1 item", kind: "page-text-equals", selector: "#count", value: "1 item" }], hints: [{ level: 1, text: "A list reports how many children it has." }, { level: 2, text: "Write list.children.length + \" item\" after the equals sign." }], xp: 50 }),
  ],
};

// Referenced so the scaffold type-checks while the course is still empty.
// Every generated project brings its own step factory and uses these.
void page;
void n;
