import type { Concept } from "@/lib/lesson-ir";

interface ConceptSeed {
  id: string;
  term: string;
  definition: string;
  analogy: string;
  proof: string;
  input: string;
  action: string;
  output: string;
}

const seeds: ConceptSeed[] = [
  { id: "design-visual-hierarchy", term: "visual hierarchy", definition: "Visual hierarchy makes the most important information easiest to notice first.", analogy: "A market sign shows the stall name large, then prices smaller, so buyers know where to look.", proof: "You will make the page title lead the reader's eye.", input: "Same-size content", action: "Rank by importance", output: "Clear reading order" },
  { id: "design-type-scale", term: "type scale", definition: "A type scale is a small set of text sizes used for clear, repeated levels.", analogy: "Road signs use a few planned sizes instead of a different size for every word.", proof: "You will apply a planned set of text sizes.", input: "Random sizes", action: "Use a scale", output: "Consistent levels" },
  { id: "design-spacing-scale", term: "spacing scale", definition: "A spacing scale is a short list of reusable gaps that keeps a page consistent.", analogy: "Floor tiles create a steady measuring grid instead of guessed distances.", proof: "You will give related and separate items planned gaps.", input: "Guessed gaps", action: "Use set gaps", output: "Steady rhythm" },
  { id: "design-proximity", term: "proximity", definition: "Proximity places related items near each other and separates unrelated groups.", analogy: "Goods for one order stay in one basket, away from the next customer's basket.", proof: "You will group a label with the information it explains.", input: "Loose items", action: "Group related items", output: "Clear groups" },
  { id: "design-alignment", term: "alignment", definition: "Alignment places edges on shared lines so information is easier to scan.", analogy: "Names on a barangay list line up in one column so each row is easy to follow.", proof: "You will align the card content to one clear edge.", input: "Drifting edges", action: "Share a line", output: "Easy scan" },
  { id: "design-whitespace", term: "whitespace", definition: "Whitespace is empty room that separates content and helps important parts breathe.", analogy: "An uncrowded counter leaves room to count change without mixing different orders.", proof: "You will add useful room around the main content.", input: "Crowded panel", action: "Add breathing room", output: "Calm focus" },
  { id: "design-readable-measure", term: "readable measure", definition: "Readable measure keeps a line of text short enough for the eye to find the next line.", analogy: "A short queue is easier to follow than one that bends across the whole terminal.", proof: "You will limit the width of a paragraph.", input: "Very long lines", action: "Limit line width", output: "Readable paragraph" },
  { id: "design-contrast-ratio", term: "contrast ratio", definition: "Contrast ratio measures how strongly text stands apart from its background.", analogy: "Black ink on white paper is easier to read than pale pencil on grey paper.", proof: "You will choose a text and background pair with strong contrast.", input: "Faint text", action: "Increase contrast", output: "Readable words" },
  { id: "design-semantic-colour", term: "semantic colour", definition: "Semantic colour gives a colour a stable job, such as action, success, or warning.", analogy: "A traffic light keeps the same meaning at every crossing.", proof: "You will use one colour role consistently across the page.", input: "Random colour", action: "Give colour a job", output: "Predictable meaning" },
  { id: "design-status-cue", term: "status cue", definition: "A status cue uses a word and a symbol so meaning never depends on colour alone.", analogy: "A clinic number board shows both the number and a spoken call.", proof: "You will add a visible word and symbol to a status.", input: "Colour only", action: "Add word and symbol", output: "Clear status" },
  { id: "design-focus-indicator", term: "focus indicator", definition: "A focus indicator shows which control will respond to the keyboard.", analogy: "A service window light shows which counter is ready for the next person.", proof: "You will give the main action a visible keyboard focus style.", input: "Hidden focus", action: "Mark current control", output: "Visible focus" },
  { id: "design-touch-target", term: "touch target", definition: "A touch target is the full area a finger can press, not only the words inside it.", analogy: "A large door handle is easier to use than a tiny latch.", proof: "You will make the main action comfortable to tap.", input: "Tiny control", action: "Enlarge press area", output: "Easy tap" },
  { id: "design-responsive-reflow", term: "responsive reflow", definition: "Responsive reflow moves content into a new arrangement when the screen gets narrow.", analogy: "Chairs move from rows into one line when a room becomes a hallway.", proof: "You will let the content stack cleanly on a phone.", input: "Wide row", action: "Rearrange for width", output: "Phone layout" },
  { id: "design-empty-state", term: "empty state", definition: "An empty state explains why nothing is shown and gives one useful next action.", analogy: "An empty shelf sign says when stock returns instead of leaving buyers guessing.", proof: "You will turn a blank panel into useful guidance.", input: "Blank panel", action: "Explain and guide", output: "Useful next step" },
  { id: "design-token", term: "design token", definition: "A design token is a named value reused for colour, spacing, type, or shape.", analogy: "A recipe names one measuring cup so every cook uses the same amount.", proof: "You will reuse named visual values across a small interface.", input: "Repeated guesses", action: "Name shared values", output: "Consistent system" },

  { id: "real-promise", term: "Promise", definition: "A Promise represents a result that will arrive later or fail.", analogy: "A claim stub is not the parcel, but it connects you to the parcel when it arrives.", proof: "You will return and resolve a Promise.", input: "Work starts", action: "Wait for result", output: "Value or error" },
  { id: "real-async-function", term: "async function", definition: "An async function always returns a Promise and can pause at await.", analogy: "A numbered service ticket lets the counter continue while your request is prepared.", proof: "You will mark a function async and read its resolved value.", input: "Function call", action: "Run async work", output: "Promise result" },
  { id: "real-await", term: "await", definition: "await pauses one async function until a Promise settles.", analogy: "You wait for your receipt before checking the total printed on it.", proof: "You will await a value before using it.", input: "Promise", action: "Await", output: "Resolved value" },
  { id: "real-try-catch", term: "try and catch", definition: "try and catch separates normal work from the response to an error.", analogy: "A delivery plan includes the normal route and a clear detour when a road is closed.", proof: "You will return a useful fallback after a failed request.", input: "Risky work", action: "Catch failure", output: "Handled result" },
  { id: "real-http-request", term: "HTTP request", definition: "An HTTP request asks another service for data or asks it to perform an action.", analogy: "An order slip says what you want and where the reply should go.", proof: "You will send a request to a lesson API fixture.", input: "App", action: "Send request", output: "Service response" },
  { id: "real-response-status", term: "response status", definition: "A response status is a number that says whether a request succeeded or why it failed.", analogy: "A claim desk stamps a form approved, missing information, or not found.", proof: "You will check response.ok and response.status.", input: "Response", action: "Read status", output: "Success or failure" },
  { id: "real-json", term: "JSON", definition: "JSON is a text format for sending structured values such as objects and arrays.", analogy: "A standard delivery form keeps every name and value in a known place.", proof: "You will read JSON from a response and store JSON safely.", input: "JSON text", action: "Parse or stringify", output: "JavaScript value" },
  { id: "real-request-method", term: "request method", definition: "A request method states the action a client wants, such as GET or POST.", analogy: "A service form is marked read, create, update, or remove before it reaches the desk.", proof: "You will send a POST request for new data.", input: "Request", action: "Choose method", output: "Clear action" },
  { id: "real-request-header", term: "request header", definition: "A request header carries information about a request, such as the body format.", analogy: "A parcel label says fragile before anyone opens the box.", proof: "You will label a JSON request body correctly.", input: "Request body", action: "Add header", output: "Known format" },
  { id: "real-url-search-params", term: "URLSearchParams", definition: "URLSearchParams builds and reads the query values after a question mark in a URL.", analogy: "A route slip adds named filters without changing the destination office.", proof: "You will build a safe search query from named values.", input: "Filter values", action: "Encode query", output: "Safe URL" },
  { id: "real-local-storage", term: "localStorage", definition: "localStorage keeps small text values in one browser after the page closes.", analogy: "A labelled drawer keeps a note ready for the next visit on the same desk.", proof: "You will save, restore, and remove one browser setting.", input: "Current value", action: "Store by key", output: "Later value" },
  { id: "real-promise-all", term: "Promise.all", definition: "Promise.all waits for several Promises and keeps their results in order.", analogy: "A report waits for every barangay desk to submit its number before adding the total.", proof: "You will load two independent records together.", input: "Several Promises", action: "Wait together", output: "Ordered results" },
  { id: "real-retry", term: "retry", definition: "A retry makes another bounded attempt after a temporary failure.", analogy: "A caller redials once after a dropped signal, then stops instead of calling forever.", proof: "You will limit repeated attempts and return the final result.", input: "Temporary failure", action: "Try again", output: "Result or stop" },

  { id: "ts-type-annotation", term: "type annotation", definition: "A type annotation states the kind of value a name may hold.", analogy: "A labelled bin says bottles only before anyone puts an item inside.", proof: "You will annotate a React value and render it.", input: "Name", action: "Add type", output: "Checked value" },
  { id: "ts-type-inference", term: "type inference", definition: "Type inference lets TypeScript work out a type from the value already present.", analogy: "Seeing rice in a clear jar tells you what belongs there without another label.", proof: "You will let TypeScript infer a safe local value.", input: "Known value", action: "Infer", output: "Known type" },
  { id: "ts-union", term: "union type", definition: "A union type allows one value to be one of several named types.", analogy: "A payment desk can accept cash or card, but not an unrelated item.", proof: "You will limit a status to a small set of valid words.", input: "Several valid kinds", action: "Join with |", output: "Limited choices" },
  { id: "ts-type-alias", term: "type alias", definition: "A type alias gives a reusable name to a TypeScript type.", analogy: "A route name stands for the full list of streets it follows.", proof: "You will name and reuse a component data shape.", input: "Type shape", action: "Give it a name", output: "Reusable type" },
  { id: "ts-interface", term: "interface", definition: "An interface names the required shape of an object.", analogy: "A permit form lists every field an accepted application must contain.", proof: "You will describe the props a component accepts.", input: "Object values", action: "Describe shape", output: "Checked object" },
  { id: "ts-optional-property", term: "optional property", definition: "An optional property may be present or absent on a typed object.", analogy: "A delivery form requires an address but leaves the landmark box optional.", proof: "You will add an optional note prop and a fallback.", input: "Object shape", action: "Mark with ?", output: "Optional value" },
  { id: "ts-readonly", term: "readonly", definition: "readonly prevents a typed property or array from being assigned a new value.", analogy: "A printed receipt can be read after payment but should not be rewritten.", proof: "You will mark incoming component data readonly.", input: "Shared data", action: "Protect from writes", output: "Read-only type" },
  { id: "ts-generic", term: "generic", definition: "A generic keeps a relationship between types while allowing many concrete values.", analogy: "One labelled tray design can carry medicine, forms, or tools without mixing their labels.", proof: "You will keep an input and output type connected.", input: "Type parameter", action: "Reuse relationship", output: "Specific result" },
  { id: "ts-narrowing", term: "type narrowing", definition: "Type narrowing uses a check to reduce several possible types to the one currently present.", analogy: "A guard checks an ID category before sending a visitor to the right line.", proof: "You will check a value before using type-specific behavior.", input: "Union value", action: "Check current kind", output: "Narrow type" },
  { id: "ts-discriminated-union", term: "discriminated union", definition: "A discriminated union gives each object shape one shared field with a distinct literal value.", analogy: "Every service ticket has a type code that determines the fields the clerk should read.", proof: "You will render different request states safely.", input: "Related object shapes", action: "Check tag field", output: "Safe branch" },
  { id: "ts-event-type", term: "event type", definition: "An event type describes the element and data carried by a browser event in React.", analogy: "A form stamp says which desk produced it and what details travel with it.", proof: "You will type an input change handler.", input: "Browser event", action: "Name event shape", output: "Safe handler" },
  { id: "ts-react-node", term: "ReactNode", definition: "ReactNode describes values React can place in the rendered tree, including text and elements.", analogy: "A display shelf can hold several approved kinds of item, not every object in the building.", proof: "You will type reusable child content.", input: "Child content", action: "Use ReactNode", output: "Renderable value" },

  { id: "test-case", term: "test case", definition: "A test case is one example with a setup, an action, and an expected result.", analogy: "A cashier checks one sample basket before opening the counter.", proof: "You will write one focused example for a function.", input: "Known setup", action: "Run one action", output: "Observed result" },
  { id: "test-assertion", term: "assertion", definition: "An assertion compares what happened with what should have happened.", analogy: "A receipt check compares the printed total with the amount you calculated.", proof: "You will make a failing comparison pass.", input: "Actual value", action: "Compare", output: "Pass or fail" },
  { id: "test-edge-case", term: "edge case", definition: "An edge case is a less common input near the limits of normal use.", analogy: "A tricycle plan should still work for the last seat, not only the first passenger.", proof: "You will add a case the first example missed.", input: "Unusual input", action: "Exercise behavior", output: "Known result" },
  { id: "test-boundary", term: "boundary value", definition: "A boundary value sits exactly where behavior changes from one rule to another.", analogy: "A fare rule changes at exactly the age printed on the sign.", proof: "You will test values immediately below, at, and above a limit.", input: "Rule limit", action: "Check around edge", output: "Correct transition" },
  { id: "test-regression", term: "regression test", definition: "A regression test preserves behavior that failed before and was later fixed.", analogy: "A repaired gate is checked with the same push that exposed the broken latch.", proof: "You will keep a previous bug from returning.", input: "Past bug", action: "Repeat failing case", output: "Protected fix" },
  { id: "test-double", term: "test double", definition: "A test double is a controlled replacement for a real dependency during a test.", analogy: "A fire drill uses a safe practice alarm instead of starting a real fire.", proof: "You will replace a request with fixed lesson data.", input: "Real dependency", action: "Use controlled stand-in", output: "Deterministic test" },
  { id: "debug-breakpoint", term: "breakpoint", definition: "A breakpoint pauses code at one line so you can inspect current values.", analogy: "A checkpoint stops a vehicle long enough to inspect its papers.", proof: "You will isolate the line where a wrong value first appears.", input: "Running code", action: "Pause at line", output: "Visible state" },
  { id: "debug-stack-trace", term: "stack trace", definition: "A stack trace lists the chain of function calls that led to an error.", analogy: "A delivery log shows every handoff before a parcel reached the wrong desk.", proof: "You will read a call chain and fix its source.", input: "Thrown error", action: "Follow calls backward", output: "Source line" },
  { id: "debug-network-panel", term: "Network panel", definition: "The Network panel shows each browser request, its timing, status, and transferred data.", analogy: "A dispatch board shows every trip, departure time, result, and load.", proof: "You will interpret a captured request record.", input: "Page requests", action: "Inspect records", output: "Request evidence" },
  { id: "debug-performance-profile", term: "performance profile", definition: "A performance profile records where browser time is spent during an interaction.", analogy: "A timed kitchen log shows which preparation step delays every order.", proof: "You will find the slowest measured task in a profile.", input: "Timed work", action: "Compare duration", output: "Largest cost" },

  { id: "cli-terminal", term: "terminal", definition: "A terminal is a window where you type commands for your computer to run, one line at a time.", analogy: "Ordering at a carinderia counter by saying exactly what you want, instead of pointing at pictures.", proof: "You type mkdir and a real folder appears on your computer.", input: "typed command", action: "computer runs it", output: "result in your folder" },
  { id: "cli-relative-path", term: "relative path", definition: "A relative path names a file by starting from the folder you are in, with a slash between each folder and file name.", analogy: "Directions that start from where you stand: second stall, then the left shelf.", proof: "You make a file inside a folder by writing folder/file as one path.", input: "current folder", action: "folder/file path", output: "the exact file" },
  { id: "cli-redirect", term: "output redirect", definition: "The > sign sends a command's text into a file, replacing whatever the file held before.", analogy: "Writing a fresh price on a small chalkboard after wiping the old price away.", proof: "You use echo with > to put your first line into a file.", input: "echo text", action: "> into a file", output: "file holds only that text" },
  { id: "cli-append", term: "append", definition: "The >> sign adds a command's text to the end of a file and keeps everything already there.", analogy: "Adding a new name at the bottom of a sign-up sheet without erasing the names above.", proof: "You add a second line with >> and the first line stays.", input: "echo text", action: ">> to the end", output: "file keeps old lines plus new" },
  { id: "cli-copy", term: "copy", definition: "cp makes a second file with the same contents, leaving the original where it was.", analogy: "Photocopying a barangay form so you can keep one and hand in the other.", proof: "You copy your list to backup.txt and both files hold the same lines.", input: "original file", action: "cp", output: "two matching files" },
  { id: "cli-move", term: "move", definition: "mv moves a file to another folder or gives it a new name. The original place no longer has it.", analogy: "Carrying a box from the front counter to the stockroom: it is in one place, never both.", proof: "You move backup.txt into archive and it disappears from the first folder.", input: "file in one folder", action: "mv", output: "file in the new place only" },
  { id: "cli-remove", term: "remove", definition: "rm deletes a file for good. rm -r deletes a folder and everything inside it. There is no recycle bin.", analogy: "Shredding an old receipt: once it is shredded you cannot take it back.", proof: "You delete the old backup and its folder, and the checker sees they are gone.", input: "file or folder", action: "rm or rm -r", output: "nothing left there" },
  { id: "git-repository", term: "Git repository", definition: "A Git repository is a project folder where Git keeps a saved history of your files in a hidden .git folder.", analogy: "A store logbook kept in the drawer, recording every change to the price list.", proof: "You run git init and your folder starts keeping history.", input: "plain folder", action: "git init", output: "folder with history" },
  { id: "git-identity", term: "Git identity", definition: "Your Git identity is the name and email Git writes on every commit, so people know who made each change.", analogy: "Signing your name in the logbook next to each entry you write.", proof: "You set user.name and user.email before your first commit.", input: "name and email", action: "git config", output: "commits signed by you" },
  { id: "git-staging", term: "staging area", definition: "The staging area holds the changes you chose for your next commit. git add puts a change there.", analogy: "Placing items on the counter before the cashier rings them up together.", proof: "You stage one file and leave another file waiting.", input: "changed file", action: "git add", output: "change ready to commit" },
  { id: "git-commit", term: "commit", definition: "A commit is a saved snapshot of your staged files, with a short message saying what changed.", analogy: "The cashier printing a receipt for exactly what was on the counter.", proof: "You commit your staged files and the repository has its first saved snapshot.", input: "staged changes", action: "git commit -m", output: "saved snapshot" },
  { id: "git-unstaged-change", term: "unstaged change", definition: "An unstaged change is an edit Git has noticed in a tracked file but that you have not added to the staging area yet.", analogy: "A new item still on the shelf: you picked it but have not put it on the counter.", proof: "You edit a committed file and the checker reports an unstaged change.", input: "edited tracked file", action: "Git compares", output: "change waiting to be staged" },
  { id: "git-amend", term: "amend", definition: "git commit --amend replaces the most recent commit, for example to fix a typing mistake in its message.", analogy: "Correcting a typo on the last receipt before handing it over, instead of printing a second one.", proof: "You fix a misspelled commit message and still have the same number of commits.", input: "last commit", action: "--amend", output: "corrected commit" },
  { id: "git-restore", term: "restore", definition: "git restore throws away unstaged edits in a file and puts back the version from the last commit.", analogy: "Tearing off a messy draft and copying the clean version from the logbook again.", proof: "You add a wrong line, restore the file, and the line is gone.", input: "unwanted edit", action: "git restore", output: "last committed version" },
  { id: "git-unstage", term: "unstage", definition: "git restore --staged takes a change back out of the staging area but keeps your edit in the file.", analogy: "Taking an item off the counter and back into your basket before you pay.", proof: "You unstage a file and its new line is still in the file.", input: "staged change", action: "git restore --staged", output: "unstaged, edit kept" },
  { id: "git-branch", term: "branch", definition: "A branch is a separate line of work in the same repository, so you can try changes without touching main.", analogy: "Trying a new menu on a separate notebook page while the posted menu stays the same.", proof: "You make a branch and main is still where you left it.", input: "main line of work", action: "git branch", output: "separate line of work" },
  { id: "git-switch", term: "switch", definition: "git switch moves you onto another branch, and your files change to match that branch.", analogy: "Flipping to a different page in the notebook to keep writing there.", proof: "You switch branches and the checker sees which branch you are on.", input: "current branch", action: "git switch", output: "files of the other branch" },
  { id: "git-merge", term: "merge", definition: "git merge brings the commits from another branch into the branch you are on.", analogy: "Copying the approved new menu items onto the posted menu.", proof: "You merge your branch and main gains its change.", input: "branch with new work", action: "git merge", output: "main has the work" },
  { id: "git-delete-branch", term: "delete a branch", definition: "git branch -d removes a branch name after its work is merged. The commits stay in history.", analogy: "Removing a finished job's tag from the board once the job is filed away.", proof: "You delete a merged branch and its change is still on main.", input: "merged branch", action: "git branch -d", output: "name gone, work kept" },
  { id: "git-mv", term: "git mv", definition: "git mv renames or moves a tracked file and stages that change so Git records it as a rename.", analogy: "Changing a shelf label and noting the change in the logbook at the same time.", proof: "You rename a file with git mv and the new name is staged.", input: "tracked file", action: "git mv", output: "staged rename" },
  { id: "git-rm", term: "git rm", definition: "git rm deletes a tracked file and stages that deletion, so the next commit records it.", analogy: "Crossing an item out of the logbook as you throw it away, so the record matches.", proof: "You remove draft.txt with git rm and the deletion is staged.", input: "tracked file", action: "git rm", output: "staged deletion" },
  { id: "git-ignore", term: ".gitignore", definition: "A .gitignore file lists name patterns that Git should never track, such as *.log for log files.", analogy: "A sign on the stockroom door: scratch paper does not go in the logbook.", proof: "You write *.log into .gitignore and commit the rule with the project.", input: "file name pattern", action: ".gitignore", output: "matching files ignored" },

  { id: "node-runtime", term: "Node.js", definition: "Node.js runs JavaScript on your computer instead of inside a web page, so a script can work with files and settings.", analogy: "The same cook can work in a restaurant kitchen or at home; the recipe language stays the same.", proof: "You run node app.js and your script prints in the terminal.", input: "app.js", action: "node app.js", output: "text in the terminal" },
  { id: "node-stderr", term: "error stream", definition: "console.error writes to a separate error stream, so warnings stay apart from normal output.", analogy: "A store keeps complaints in a separate notebook from the daily sales list.", proof: "You print a low-stock warning with console.error.", input: "warning text", action: "console.error", output: "error stream" },
  { id: "node-export", term: "export", definition: "export makes a value in one file available to other files.", analogy: "Posting a price list on the door so neighboring stalls can read it.", proof: "You export the store name from prices.js.", input: "value in prices.js", action: "export", output: "shareable value" },
  { id: "node-import", term: "import", definition: "import brings an exported value from another file into this one.", analogy: "Copying a neighbor's posted price into your own notebook.", proof: "You import storeName into app.js and print it.", input: "exported value", action: "import", output: "value in app.js" },
  { id: "node-default-export", term: "default export", definition: "A default export is the one main value a file offers, imported without curly braces.", analogy: "A stall known for one main dish, so you just ask for the usual.", proof: "You import formatPeso without braces and use it.", input: "main function", action: "export default", output: "import without braces" },
  { id: "node-builtin-module", term: "built-in module", definition: "A built-in module comes with Node, such as node:fs or node:os, so there is nothing to install.", analogy: "The tools that come with a new stall, before you buy anything extra.", proof: "You import platform from node:os and print your system name.", input: "node: name", action: "import", output: "ready-made tools" },
  { id: "npm-script", term: "npm script", definition: "An npm script is a named command in package.json that you run with npm run.", analogy: "A labeled switch that starts the rice cooker without remembering the steps.", proof: "You add a start script and run npm run start.", input: "package.json scripts", action: "npm run start", output: "your command runs" },
  { id: "node-import-alias", term: "import alias", definition: "as gives an imported value a different name inside your file.", analogy: "Calling a regular customer by a nickname in your own notes.", proof: "You import priceOf as lookup and call lookup.", input: "priceOf", action: "import as", output: "lookup" },
  { id: "node-read-file", term: "readFile", definition: "readFile from node:fs/promises reads a whole file as text, and await waits for it to finish.", analogy: "Asking a helper to fetch the ledger and waiting until they bring it back.", proof: "You read stock.txt and print its lines.", input: "stock.txt", action: "await readFile", output: "file text" },
  { id: "node-split-lines", term: "split into lines", definition: "text.split(\"\\n\") cuts text into an array of lines at each line break.", analogy: "Cutting a long receipt into one strip per item.", proof: "You split the stock text and count the lines.", input: "whole text", action: "split", output: "array of lines" },
  { id: "node-write-file", term: "writeFile", definition: "writeFile saves text to a file, creating it or replacing what it held.", analogy: "Writing a fresh summary sheet and filing it.", proof: "You write report.txt with the number of items.", input: "text", action: "await writeFile", output: "saved file" },
  { id: "node-json-file", term: "JSON file", definition: "JSON.stringify turns objects into text you can save, and JSON.parse turns that text back into objects.", analogy: "Packing items into labeled boxes for storage, then unpacking them later.", proof: "You save the items to stock.json and read them back.", input: "objects", action: "stringify and parse", output: "objects again" },
  { id: "node-append-file", term: "appendFile", definition: "appendFile adds text to the end of a file and keeps what is already there.", analogy: "Adding a new line to the bottom of a logbook page.", proof: "You add Checked today to report.txt.", input: "new line", action: "appendFile", output: "longer file" },
  { id: "node-error-code", term: "error code", definition: "A Node error carries a short code, such as ENOENT for a file that does not exist, so you can react to it.", analogy: "A return slip marked address not found instead of a vague note.", proof: "You catch a missing-file error and print its code.", input: "failed read", action: "catch", output: "ENOENT" },
  { id: "node-top-level-await", term: "top-level await", definition: "In a module, await can pause the file itself until a promise finishes.", analogy: "Waiting at the counter until the rice is cooked before serving.", proof: "You wait 100 milliseconds before printing After wait.", input: "promise", action: "await", output: "code continues after" },
  { id: "node-promise-race", term: "Promise.race", definition: "Promise.race settles with whichever promise finishes first.", analogy: "Two tricycles leave at once; the first to arrive decides who gets the fare.", proof: "You race a slow and a fast promise and print the winner.", input: "several promises", action: "Promise.race", output: "first result" },
  { id: "node-rejected-promise", term: "rejected promise", definition: "A rejected promise means the work failed; try and catch around await handles the failure.", analogy: "A supplier calls to say the delivery cannot come today.", proof: "You catch Supplier offline and report it.", input: "failing work", action: "try and catch", output: "handled error" },
  { id: "node-all-settled", term: "Promise.allSettled", definition: "Promise.allSettled waits for every promise and reports which worked and which failed.", analogy: "A report listing every delivery as arrived or cancelled.", proof: "You print fulfilled and rejected for two lookups.", input: "mixed promises", action: "allSettled", output: "every status" },
  { id: "node-finally", term: "finally", definition: "A finally block runs after try, whether the work succeeded or failed.", analogy: "Closing the stall shutters at night whether sales were good or bad.", proof: "You print Cleanup done from a finally block.", input: "try block", action: "finally", output: "always runs" },
  { id: "node-interval", term: "setInterval", definition: "setInterval repeats a function every few milliseconds until clearInterval stops it.", analogy: "A guard who checks the gate every hour until the shift ends.", proof: "You count three ticks and stop the interval.", input: "repeating task", action: "setInterval", output: "stopped after 3" },
  { id: "node-event-loop", term: "event loop", definition: "Node finishes the code in front of it before running waiting timers, even a zero-delay one.", analogy: "A cashier finishes the current customer before calling the next number.", proof: "Sync done prints before Timer done.", input: "timer and code", action: "event loop", output: "code first, timer next" },
  { id: "node-argv", term: "process.argv", definition: "process.argv holds the words typed after node app.js, so a script can take input from the command.", analogy: "An order slip that says what the customer wants before cooking starts.", proof: "You print how many words were typed.", input: "typed words", action: "process.argv", output: "array of words" },
  { id: "node-exit-code", term: "exit code", definition: "An exit code is a number a program ends with: 0 means it worked, other numbers mean a problem.", analogy: "A green or red light on the counter when a transaction ends.", proof: "Your tool ends with code 1 when no item is typed.", input: "problem found", action: "process.exit", output: "non-zero code" },
  { id: "node-cli-flag", term: "command-line flag", definition: "A flag such as --receipt is an optional word that switches a feature on.", analogy: "Asking for a receipt only when you need one.", proof: "You print a receipt line only when --receipt is typed.", input: "--receipt", action: "check args", output: "extra output" },
  { id: "node-env-var", term: "environment variable", definition: "An environment variable is a named setting outside your code that process.env reads.", analogy: "A note on the stall door that changes the day's hours without rewriting the menu.", proof: "You print the PLACE setting the checker gives you.", input: "PLACE=...", action: "process.env", output: "setting in code" },
  { id: "node-default-value", term: "default value", definition: "?? picks a fallback value when a setting is missing.", analogy: "Serving the house blend when the customer does not name a coffee.", proof: "Without PLACE, your script prints Unknown place.", input: "missing setting", action: "??", output: "fallback" },
  { id: "node-required-setting", term: "required setting", definition: "A required setting must exist, so the program stops early with a clear message when it is missing.", analogy: "A cashier who will not open the drawer without the key.", proof: "Your script exits with code 1 when API_KEY is missing.", input: "missing API_KEY", action: "check and exit", output: "clear stop" },
  { id: "node-secret", term: "secret", definition: "A secret, such as an API key, must never be printed in full or written into your code.", analogy: "You show the last digits of a card number, never the whole thing.", proof: "You print only the first two characters of the key.", input: "API_KEY", action: "mask", output: "sk***" },
  { id: "node-config-file", term: "config file", definition: "A config file holds settings as data, such as JSON, so they can change without editing code.", analogy: "A price board you update without rebuilding the stall.", proof: "You read the currency from config.json.", input: "config.json", action: "read and parse", output: "settings" },
  { id: "node-setting-order", term: "setting priority", definition: "When a setting can come from two places, one must win; here the environment overrides the file.", analogy: "The manager's note for today beats the printed weekly schedule.", proof: "CURRENCY=USD overrides the PHP in config.json.", input: "env and file", action: "?? order", output: "one value" },
  { id: "node-env-mode", term: "NODE_ENV", definition: "NODE_ENV is a common setting that says whether a program runs in development or production.", analogy: "Practice day versus opening day at the stall.", proof: "With NODE_ENV=production your script prints Mode: production.", input: "NODE_ENV", action: "compare", output: "mode" },
  { id: "node-path-join", term: "path.join", definition: "path.join builds a file path with the right separator for the computer it runs on.", analogy: "Writing an address in the format the local post office expects.", proof: "You build records/a.txt with path.join.", input: "folder and file names", action: "path.join", output: "correct path" },
  { id: "node-extname", term: "file extension", definition: "path.extname returns the ending of a file name, such as .txt, which usually tells the file type.", analogy: "The label color on a jar that tells you what is inside.", proof: "You print Extension: .txt.", input: "a.txt", action: "path.extname", output: ".txt" },
  { id: "node-readdir", term: "readdir", definition: "readdir lists the names inside a folder.", analogy: "Opening a drawer and reading every folder tab.", proof: "You count the entries in the records folder.", input: "folder", action: "readdir", output: "list of names" },
  { id: "node-mkdir", term: "mkdir in code", definition: "mkdir with recursive: true makes a folder and does not fail if it already exists.", analogy: "Setting up a storage box only if there is not one there already.", proof: "Your script makes the archive folder.", input: "folder name", action: "mkdir", output: "folder ready" },
  { id: "node-copy-file", term: "copyFile", definition: "copyFile makes a second copy of a file at a new path.", analogy: "Photocopying a record before filing the original.", proof: "You copy records/a.txt into archive.", input: "file", action: "copyFile", output: "second copy" },
  { id: "node-stat", term: "stat", definition: "stat reads details about a file, such as its size in bytes, without reading its contents.", analogy: "Weighing a parcel without opening it.", proof: "You print the size of records/a.txt.", input: "file", action: "stat", output: "size and details" },
  { id: "node-rename", term: "rename", definition: "rename moves or renames a file in one step.", analogy: "Relabeling a jar on the shelf.", proof: "You rename the archived copy to a-old.txt.", input: "old name", action: "rename", output: "new name" },
  { id: "node-absolute-path", term: "absolute path", definition: "An absolute path starts from the top of the computer's drive; path.resolve turns a relative path into one.", analogy: "A full home address instead of 'two houses down'.", proof: "You confirm path.resolve gives an absolute path.", input: "relative path", action: "path.resolve", output: "full path" },
];

function buildConcept(seed: ConceptSeed): Concept {
  return {
    id: seed.id,
    term: seed.term,
    definition: seed.definition,
    analogy: seed.analogy,
    visual: {
      kind: "diagram",
      diagram: {
        alt: `${seed.input} moves through ${seed.action} and becomes ${seed.output}.`,
        columns: 3,
        nodes: [
          { id: "input", label: seed.input, tone: "ghost" },
          { id: "action", label: seed.action, tone: "accent" },
          { id: "output", label: seed.output, tone: "box" },
        ],
        arrows: [
          { from: "input", to: "action" },
          { from: "action", to: "output" },
        ],
      },
    },
    proof: seed.proof,
  };
}

export const newCourseConcepts: Record<string, Concept> = Object.fromEntries(
  seeds.map((seed) => [seed.id, buildConcept(seed)]),
);
