import type { Course } from "@/lib/lesson-ir";
import type { PracticeActivity } from "@/lib/practice-ir";

export const practiceActivities: PracticeActivity[] = [
  {
    id: "rebuild-community-notice",
    index: 1,
    projectId: "rebuild-community-notice",
    sourceCourseId: "html-basics",
    sourceProjectId: "sari-sari-store-page",
    mode: "rebuild",
    title: "Rebuild a community notice",
    summary: "Recall the smallest useful page structure without step-by-step blocks.",
    task: "Build a notice with one clear heading and one paragraph that explains the update.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<!DOCTYPE html>\n<html>\n  <head><title>Community Notice</title></head>\n  <body>\n\n  </body>\n</html>",
      "styles.css": "",
    },
    activeFile: "index.html",
    tests: [
      { id: "notice-heading", kind: "text-not-empty", selector: "h1", label: "The notice has one clear heading" },
      { id: "notice-details", kind: "text-not-empty", selector: "p", label: "The notice explains the update" },
    ],
    hints: [
      { level: 1, text: "Think about the two text elements a short notice needs before any styling." },
      { level: 2, text: "Use an h1 for the heading and a p for the explanation." },
    ],
    xp: 0,
    estimatedMinutes: 8,
    solution: {
      "index.html": "<!DOCTYPE html>\n<html>\n  <head><title>Community Notice</title></head>\n  <body>\n    <h1>Water interruption</h1>\n    <p>Service returns at 4 PM today.</p>\n  </body>\n</html>",
      "styles.css": "",
    },
  },
  {
    id: "rebuild-readable-card",
    index: 2,
    projectId: "rebuild-readable-card",
    sourceCourseId: "css-basics",
    sourceProjectId: "barangay-service-cards",
    mode: "rebuild",
    title: "Rebuild a readable service card",
    summary: "Use a few remembered CSS decisions to keep one card readable on a phone.",
    task: "Keep the service card within 360 pixels and add 16 pixels of space inside it.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<article class=\"service-card\"><h1>Barangay Services</h1><p>Open Monday to Friday.</p></article>",
      "styles.css": ".service-card {\n\n}",
    },
    activeFile: "styles.css",
    tests: [
      { id: "card-width", kind: "style", selector: ".service-card", prop: "max-width", equals: "360px", readable: "360 pixels", label: "The card stays readable on a phone" },
      { id: "card-padding", kind: "style", selector: ".service-card", prop: "padding-top", equals: "16px", readable: "16 pixels", label: "The card has inside space" },
    ],
    hints: [
      { level: 1, text: "Both requirements belong inside the existing service-card rule." },
      { level: 2, text: "Add max-width: 360px and padding: 16px." },
    ],
    xp: 0,
    estimatedMinutes: 8,
    solution: {
      "index.html": "<article class=\"service-card\"><h1>Barangay Services</h1><p>Open Monday to Friday.</p></article>",
      "styles.css": ".service-card {\n  max-width: 360px;\n  padding: 16px;\n}",
    },
  },
  {
    id: "bug-clinic-fare-total",
    index: 3,
    projectId: "bug-clinic-fare-total",
    sourceCourseId: "js-basics",
    sourceProjectId: "palengke-price-counter",
    mode: "bug-clinic",
    title: "Bug Clinic: wrong fare total",
    summary: "Repair a common accumulator mistake without replacing the whole function.",
    task: "The fare total is going down instead of up. Repair the smallest wrong operation.",
    kind: "js",
    inputMode: "guided",
    files: {
      "script.js": "function totalFares(fares) {\n  return fares.reduce((total, fare) => total - fare, 0);\n}\n\nconsole.log(totalFares([13, 15, 20]));",
    },
    activeFile: "script.js",
    highlightToken: "total - fare",
    tests: [
      { id: "fare-total", kind: "js-returns", fn: "totalFares", args: [[13, 15, 20]], equals: 48, label: "The three fares total 48" },
    ],
    hints: [
      { level: 1, text: "Follow the value of total after each fare. One operator moves it the wrong way." },
      { level: 2, text: "The reducer should add each fare to total." },
    ],
    xp: 0,
    estimatedMinutes: 6,
    solution: {
      "script.js": "function totalFares(fares) {\n  return fares.reduce((total, fare) => total + fare, 0);\n}\n\nconsole.log(totalFares([13, 15, 20]));",
    },
  },
  {
    id: "bug-clinic-counter-button",
    index: 4,
    projectId: "bug-clinic-counter-button",
    sourceCourseId: "react-basics",
    sourceProjectId: "barangay-queue-counter",
    mode: "bug-clinic",
    title: "Bug Clinic: counter moves backward",
    summary: "Trace one event handler and repair the state update that has the wrong direction.",
    task: "The Add button subtracts one. Repair the handler so the displayed count becomes 1 after one click.",
    kind: "react",
    inputMode: "guided",
    files: {
      "app.js": "function App() {\n  const [count, setCount] = React.useState(0);\n  return React.createElement(\"button\", { onClick: () => setCount(count - 1) }, `Add: ${count}`);\n}",
    },
    activeFile: "app.js",
    highlightToken: "count - 1",
    tests: [
      { id: "counter-adds", kind: "react-click-text-equals", clickSelector: "button", selector: "button", value: "Add: 1", label: "One click raises the count to 1" },
    ],
    hints: [
      { level: 1, text: "Read the operator inside setCount and compare its direction with the button label." },
      { level: 2, text: "Add one to count instead of subtracting one." },
    ],
    xp: 0,
    estimatedMinutes: 6,
    solution: {
      "app.js": "function App() {\n  const [count, setCount] = React.useState(0);\n  return React.createElement(\"button\", { onClick: () => setCount(count + 1) }, `Add: ${count}`);\n}",
    },
  },
  {
    id: "constraint-keyboard-help-link",
    index: 5,
    projectId: "constraint-keyboard-help-link",
    sourceCourseId: "css-basics",
    sourceProjectId: "emergency-help-link",
    mode: "constraint",
    title: "Constraint Mission: keyboard help link",
    summary: "Meet two practical access requirements without changing the link into a custom control.",
    task: "Give the emergency link a real phone destination and a visible keyboard focus outline.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<a class=\"help-link\">Call the barangay desk</a>",
      "styles.css": ".help-link {\n  color: #b91c1c;\n}",
    },
    activeFile: "index.html",
    tests: [
      { id: "help-phone-link", kind: "attr-equals", selector: ".help-link", attr: "href", value: "tel:+63281234567", label: "The help link has a phone destination" },
      { id: "help-focus-visible", kind: "source-matches", file: "styles.css", pattern: "\\.help-link:focus-visible\\s*\\{[^}]*outline\\s*:\\s*3px\\s+solid\\s+#111827", flags: "is", because: "Use a focus-visible rule with a three-pixel solid outline.", label: "Keyboard focus has a visible outline" },
    ],
    constraints: [
      { id: "real-destination", label: "Real destination", description: "The link must use a phone URL people can activate.", testIds: ["help-phone-link"] },
      { id: "visible-focus", label: "Visible keyboard focus", description: "The link must show where keyboard focus is.", testIds: ["help-focus-visible"] },
    ],
    hints: [
      { level: 1, text: "One requirement belongs in the link tag. The other belongs in a focus-visible rule." },
      { level: 2, text: "Add href=\"tel:+63281234567\" and a 3px solid #111827 outline for focus-visible." },
    ],
    xp: 0,
    estimatedMinutes: 8,
    solution: {
      "index.html": "<a class=\"help-link\" href=\"tel:+63281234567\">Call the barangay desk</a>",
      "styles.css": ".help-link {\n  color: #b91c1c;\n}\n\n.help-link:focus-visible { outline: 3px solid #111827; }",
    },
  },
  {
    id: "constraint-print-notice",
    index: 6,
    projectId: "constraint-print-notice",
    sourceCourseId: "css-basics",
    sourceProjectId: "barangay-print-notice",
    mode: "constraint",
    title: "Constraint Mission: printable notice",
    summary: "Add a narrow print rule without claiming to simulate every printer.",
    task: "For print output, remove the dark background and make the notice text black.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<article class=\"notice\"><h1>Water Schedule</h1><p>Zone 2: 2 PM</p></article>",
      "styles.css": ".notice {\n  background: #0f172a;\n  color: white;\n}",
    },
    activeFile: "styles.css",
    tests: [
      { id: "notice-print-background", kind: "source-matches", file: "styles.css", pattern: "@media\\s+print\\s*\\{[\\s\\S]*?\\.notice\\s*\\{[^}]*background(?:-color)?\\s*:\\s*(?:white|transparent)", flags: "i", because: "Put a light or transparent background inside a print media rule.", label: "Print output removes the dark background" },
      { id: "notice-print-text", kind: "source-matches", file: "styles.css", pattern: "@media\\s+print\\s*\\{[\\s\\S]*?\\.notice\\s*\\{[^}]*color\\s*:\\s*(?:black|#000(?:000)?)", flags: "i", because: "Set black text inside the print media rule.", label: "Print output uses black text" },
    ],
    constraints: [
      { id: "print-colours", label: "Readable print colours", description: "The authored print rule must remove the dark background and use black text.", testIds: ["notice-print-background", "notice-print-text"] },
    ],
    hints: [
      { level: 1, text: "Keep the screen rule. Add a separate rule that applies only when the page is printed." },
      { level: 2, text: "Inside @media print, set the notice background to white and its color to black." },
    ],
    xp: 0,
    estimatedMinutes: 8,
    solution: {
      "index.html": "<article class=\"notice\"><h1>Water Schedule</h1><p>Zone 2: 2 PM</p></article>",
      "styles.css": ".notice {\n  background: #0f172a;\n  color: white;\n}\n\n@media print { .notice { background: white; color: black; } }",
    },
  },
  {
    id: "remix-community-notice",
    index: 7,
    projectId: "remix-community-notice",
    sourceCourseId: "html-basics",
    sourceProjectId: "sari-sari-store-page",
    sourceActivityId: "rebuild-community-notice",
    mode: "remix",
    title: "Remix the community notice",
    summary: "Clone a completed notice and transfer its structure to a different local need.",
    task: "Change the cloned notice into a Barangay Cleanup announcement that mentions Saturday.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<!DOCTYPE html>\n<html>\n  <head><title>Community Notice</title></head>\n  <body>\n    <h1>Water interruption</h1>\n    <p>Service returns at 4 PM today.</p>\n  </body>\n</html>",
      "styles.css": "",
    },
    activeFile: "index.html",
    tests: [
      { id: "remix-cleanup-heading", kind: "text-equals", selector: "h1", value: "Barangay Cleanup", label: "The remixed notice names the cleanup" },
      { id: "remix-saturday", kind: "text-contains", selector: "p", value: "Saturday", label: "The remixed notice includes Saturday" },
    ],
    constraints: [
      { id: "new-subject", label: "New subject", description: "The remix must change both the heading and the useful detail.", testIds: ["remix-cleanup-heading", "remix-saturday"] },
    ],
    hints: [
      { level: 1, text: "Keep the working page structure. Change only the subject and the useful detail." },
      { level: 2, text: "Use Barangay Cleanup as the heading and mention Saturday in the paragraph." },
    ],
    xp: 0,
    estimatedMinutes: 6,
    solution: {
      "index.html": "<!DOCTYPE html>\n<html>\n  <head><title>Community Notice</title></head>\n  <body>\n    <h1>Barangay Cleanup</h1>\n    <p>Meet at the covered court this Saturday.</p>\n  </body>\n</html>",
      "styles.css": "",
    },
  },
  {
    id: "remix-readable-card",
    index: 8,
    projectId: "remix-readable-card",
    sourceCourseId: "css-basics",
    sourceProjectId: "barangay-service-cards",
    sourceActivityId: "rebuild-readable-card",
    mode: "remix",
    title: "Remix the service card",
    summary: "Keep a completed card's readable frame while changing its content and emphasis.",
    task: "Turn the cloned card into a Health Centre card and make its heading dark teal.",
    kind: "web",
    inputMode: "free",
    files: {
      "index.html": "<article class=\"service-card\"><h1>Barangay Services</h1><p>Open Monday to Friday.</p></article>",
      "styles.css": ".service-card {\n  max-width: 360px;\n  padding: 16px;\n}",
    },
    activeFile: "index.html",
    tests: [
      { id: "remix-health-title", kind: "text-equals", selector: "h1", value: "Health Centre", label: "The remixed card names the Health Centre" },
      { id: "remix-health-colour", kind: "style", selector: "h1", prop: "color", equals: "rgb(15, 118, 110)", readable: "dark teal", label: "The remixed heading is dark teal" },
    ],
    constraints: [
      { id: "preserve-readable-frame", label: "Preserve the readable frame", description: "Start from the completed card copy and change its subject without editing the source draft.", testIds: ["remix-health-title", "remix-health-colour"] },
    ],
    hints: [
      { level: 1, text: "The content change belongs in HTML. The heading emphasis belongs in CSS." },
      { level: 2, text: "Change the h1 text to Health Centre and set h1 color to #0f766e." },
    ],
    xp: 0,
    estimatedMinutes: 7,
    solution: {
      "index.html": "<article class=\"service-card\"><h1>Health Centre</h1><p>Open Monday to Friday.</p></article>",
      "styles.css": ".service-card {\n  max-width: 360px;\n  padding: 16px;\n}\n\nh1 { color: #0f766e; }",
    },
  },
];

export const practiceCourse: Course = {
  id: "practice-modes",
  title: "Rebuild Mode and Bug Clinic",
  project: "Independent Practice",
  projects: practiceActivities.map((activity) => ({ id: activity.projectId, title: activity.title })),
  order: 11,
  summary: "Optional recall and debugging activities checked by the same browser grader.",
  requires: [],
  kind: "web",
  steps: practiceActivities,
};
