<#
  run-qwen-loop.ps1 — local-model driver for the CodeDaddy autonomous build loop.

  WHAT THIS IS

  Same idea as run-codex-loop.ps1, but the model runs on this machine through
  LM Studio instead of a paid API. Nothing here spends credits: `codex --oss
  --local-provider lmstudio` points the CLI at http://localhost:1234, and every
  token is generated by the local GPU.

  WHY IT IS STRICTER THAN THE PAID LOOP

  A 7B local model drifts more than a frontier model does, and nobody is
  watching overnight. So this driver does not trust the model to police itself:

    - It verifies AGENTS.md and PLAN.md are untouched after every pass, and
      restores them if they are not. The paid loop deleted AGENTS.md once.
    - It runs tsc and eslint after every pass and reverts the pass if either
      goes red, so a broken tree never compounds into the next pass.
    - It commits a checkpoint every $CommitEvery passes, so work is never left
      sitting uncommitted the way 8,200 lines were on 2026-08-26.

  USAGE

    Start LM Studio's server first (or let this script do it):
      lms server start

    powershell -ExecutionPolicy Bypass -File .\run-qwen-loop.ps1

  STOP IT

    New-Item -ItemType File STOP_LOOP     (finishes the current pass, then ends)
    or Ctrl+C                             (kills it now)

  Logs land in .codex-loop-logs\qwen-*.log.
#>

param(
  [int]$MaxIterations = 500,
  [int]$PauseSeconds  = 5,

  # Commit a checkpoint every N successful passes. Lower than you think it
  # should be: the point is that a bad night costs one checkpoint, not a week.
  [int]$CommitEvery   = 5,

  # Must match the model id LM Studio reports at /v1/models once loaded.
  [string]$Model      = "qwen2.5-coder-7b-instruct",

  [string]$LmsUrl     = "http://localhost:1234"
)

$ErrorActionPreference = "Continue"

$repo       = $PSScriptRoot
$promptFile = Join-Path $repo "CODEX_LOOP_PROMPT.md"
$stopFile   = Join-Path $repo "STOP_LOOP"
$logDir     = Join-Path $repo ".codex-loop-logs"
$lastMsg    = Join-Path $logDir "qwen-last-message.txt"
$webDir     = Join-Path $repo "apps\web"

# Files the model must never modify. It is told this in the prompt; this list
# is what enforces it when the model ignores the prompt.
$guarded = @("AGENTS.md", "PLAN.md")

if (-not (Test-Path $promptFile)) { Write-Error "Missing $promptFile"; exit 1 }
if (-not (Test-Path $logDir))     { New-Item -ItemType Directory -Path $logDir | Out-Null }
if (Test-Path $stopFile)          { Remove-Item $stopFile -Force; Write-Host "Cleared stale STOP_LOOP." }

Set-Location $repo

# --- preflight ---------------------------------------------------------------

Write-Host ""
Write-Host "CodeDaddy local-model build loop (Qwen via LM Studio)" -ForegroundColor Cyan
Write-Host "Repo:        $repo"
Write-Host "Model:       $Model"
Write-Host "Endpoint:    $LmsUrl  (local — no credits, no API key)"
Write-Host "Max passes:  $MaxIterations"
Write-Host "Commit every: $CommitEvery passes"
Write-Host "Stop with:   New-Item -ItemType File STOP_LOOP"
Write-Host ""

try {
  $models = Invoke-RestMethod -Uri "$LmsUrl/v1/models" -TimeoutSec 10
  $ids    = $models.data | ForEach-Object { $_.id }
  if ($ids -notcontains $Model) {
    Write-Host "Model '$Model' is not loaded in LM Studio." -ForegroundColor Red
    Write-Host "Loaded right now:" -ForegroundColor Yellow
    $ids | ForEach-Object { Write-Host "  $_" }
    Write-Host "Load it with:  lms load $Model" -ForegroundColor Yellow
    exit 1
  }
  Write-Host "LM Studio is serving '$Model'." -ForegroundColor Green
} catch {
  Write-Host "Cannot reach LM Studio at $LmsUrl. Start it with:  lms server start" -ForegroundColor Red
  exit 1
}

if ((git status --porcelain).Length -gt 0) {
  Write-Host "Working tree is dirty. Commit or stash before starting the loop," -ForegroundColor Red
  Write-Host "otherwise a bad pass cannot be told apart from your own edits." -ForegroundColor Red
  exit 1
}

$common = @(
  "--oss",
  "--local-provider", "lmstudio",
  "-m", $Model,
  "-c", 'sandbox_mode="workspace-write"',
  "-c", 'approval_policy="never"'
)

$continueMsg = @'
Continue the loop from section 2 of CODEX_LOOP_PROMPT.md.

Do not summarize the last pass. Do not ask whether to proceed. Re-read PLAN.md
section 8, pick up from your own NEXT: line, and execute the next batch with the
static gates green.

Never edit AGENTS.md or PLAN.md. They are the rules and the plan, not your
output. If you believe one of them is wrong, say so in your NEXT: line and
change nothing.

Browser QA stays deferred per section 5a. A large PENDING_QA.md is expected and
never pauses authoring. If the browser is unreachable, log one line and author
anyway. If nothing seems actionable, walk the ladder in section 5b.
'@

# --- helpers -----------------------------------------------------------------

function Test-GuardedFiles {
  # Returns $true when every guarded file is untouched.
  $dirty = git status --porcelain -- $guarded
  if ($dirty) {
    Write-Host "  GUARD: the model touched a protected file:" -ForegroundColor Red
    $dirty | ForEach-Object { Write-Host "    $_" -ForegroundColor Red }
    git checkout HEAD -- $guarded 2>&1 | Out-Null
    Write-Host "  GUARD: restored from HEAD." -ForegroundColor Yellow
    return $false
  }
  return $true
}

function Test-StaticGates {
  # tsc and eslint only. `next build` is too slow to run 500 times, and the
  # curriculum harness needs a real browser, so it stays a freeze-time gate.
  Push-Location $webDir
  try {
    npx tsc --noEmit 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Host "  GATE: tsc failed." -ForegroundColor Red; return $false }
    npx eslint . 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Host "  GATE: eslint failed." -ForegroundColor Red; return $false }
    return $true
  } finally { Pop-Location }
}

function Get-StepCount {
  (Select-String -Path "apps\web\content\*-course.ts" -Pattern 'xp:\s*\d+' -AllMatches |
   Measure-Object).Count
}

# --- loop --------------------------------------------------------------------

$consecutiveFailures = 0
$passesSinceCommit   = 0
$startSteps          = Get-StepCount

Write-Host "Starting at $startSteps steps." -ForegroundColor DarkGray
Write-Host ""

for ($i = 1; $i -le $MaxIterations; $i++) {

  if (Test-Path $stopFile) {
    Write-Host "STOP_LOOP found. Ending after $($i - 1) passes." -ForegroundColor Yellow
    break
  }

  $stamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
  $log   = Join-Path $logDir ("qwen-pass-{0:d3}-{1}.log" -f $i, $stamp)

  Write-Host "--- pass $i of $MaxIterations  ($stamp) ---" -ForegroundColor Green

  if ($i -eq 1) {
    Get-Content $promptFile -Raw |
      codex exec @common --output-last-message $lastMsg - 2>&1 |
      Tee-Object -FilePath $log
  } else {
    codex exec resume --last @common --output-last-message $lastMsg $continueMsg 2>&1 |
      Tee-Object -FilePath $log
  }

  $code = $LASTEXITCODE

  if ($code -ne 0) {
    $consecutiveFailures++
    Write-Host "codex exited $code (failure $consecutiveFailures in a row)." -ForegroundColor Yellow
    if ($consecutiveFailures -ge 3) {
      Write-Host "Three consecutive failures. Stopping. See $log" -ForegroundColor Red
      break
    }
    Start-Sleep -Seconds 30
    continue
  }

  $consecutiveFailures = 0

  # --- post-pass verification ---
  # Order matters: restore guarded files first, then judge the rest of the tree.

  $guardOk = Test-GuardedFiles
  $gatesOk = Test-StaticGates

  if (-not $gatesOk) {
    # A red tree poisons every later pass, so throw this one away rather than
    # asking a 7B model to debug its own mess at 3am.
    Write-Host "  Reverting pass $i (static gates red)." -ForegroundColor Yellow
    git checkout -- . 2>&1 | Out-Null
    git clean -fd apps/web/content 2>&1 | Out-Null
    $consecutiveFailures++
    if ($consecutiveFailures -ge 3) {
      Write-Host "Three reverted passes in a row. The model is not producing usable work. Stopping." -ForegroundColor Red
      break
    }
    Start-Sleep -Seconds $PauseSeconds
    continue
  }

  if (-not $guardOk) {
    Write-Host "  Pass $i kept, but its edit to a protected file was undone." -ForegroundColor Yellow
  }

  # --- progress readout ---

  if (Test-Path $lastMsg) {
    $next = (Get-Content $lastMsg -Raw) -split "`n" |
            Where-Object { $_ -match '^\s*NEXT:' } |
            Select-Object -Last 1
    if ($next) { Write-Host ("  " + $next.Trim()) -ForegroundColor DarkCyan }
  }

  $steps = Get-StepCount
  Write-Host "  pass $i done. steps: $steps (+$($steps - $startSteps) this run)" -ForegroundColor DarkGray

  # --- checkpoint ---

  $passesSinceCommit++
  if ($passesSinceCommit -ge $CommitEvery -and (git status --porcelain).Length -gt 0) {
    git add -A 2>&1 | Out-Null
    $msg = "Curriculum authoring checkpoint: $steps steps (local Qwen loop, passes through $i)"
    git commit -m $msg 2>&1 | Out-Null
    Write-Host "  Committed checkpoint at $steps steps." -ForegroundColor DarkGreen
    $passesSinceCommit = 0
  }

  if (Test-Path $stopFile) {
    Write-Host "STOP_LOOP found. Ending after $i passes." -ForegroundColor Yellow
    break
  }

  Start-Sleep -Seconds $PauseSeconds
}

# Never leave the last stretch of work uncommitted.
if ((git status --porcelain).Length -gt 0) {
  $steps = Get-StepCount
  git add -A 2>&1 | Out-Null
  git commit -m "Curriculum authoring checkpoint: $steps steps (local Qwen loop, final)" 2>&1 | Out-Null
  Write-Host "Committed final checkpoint at $steps steps." -ForegroundColor DarkGreen
}

Write-Host ""
Write-Host "Loop finished. Logs in $logDir" -ForegroundColor Cyan
